/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=/dev/null --include-runtime=false --strict-vars=false --env-interface=DatabaseBindings worker-configuration.generated.d.ts` (hash: 9d7318f87681c307e4af4aafc2519bfd)
interface __BaseEnv_DatabaseBindings {
	HYPERDRIVE_FRESH: Hyperdrive;
	HYPERDRIVE_CACHED: Hyperdrive;
	ACCOUNTS_EMAIL_QUEUE: Queue;
	ACCOUNTS_AUTH_SECRET: SecretsStoreSecret;
	ACCOUNTS_IP_HASH_SALT: SecretsStoreSecret;
	ACCOUNTS_TURNSTILE_SECRET: SecretsStoreSecret;
	ACCOUNTS_GOOGLE_CLIENT_SECRET: SecretsStoreSecret;
	ACCOUNTS_KAKAO_CLIENT_SECRET: SecretsStoreSecret;
	ACCOUNTS_BBATON_CLIENT_SECRET: SecretsStoreSecret;
	ACCOUNTS_RESEND_API_KEY: SecretsStoreSecret;
	STELLA_TURNSTILE_SECRET: SecretsStoreSecret;
	STELLA_IP_HASH_SALT: SecretsStoreSecret;
	STELLA_DISCORD_WEBHOOK: SecretsStoreSecret;
	STELLA_RESEND_API_KEY: SecretsStoreSecret;
	STELLA_AUTH_SECRET: SecretsStoreSecret;
	STELLA_OIDC_CLIENT_SECRET: SecretsStoreSecret;
	DEEPTYPE_ANTHROPIC_API_KEY: SecretsStoreSecret;
	DEEPTYPE_RESEND_API_KEY: SecretsStoreSecret;
	DEEPTYPE_TURNSTILE_SECRET: SecretsStoreSecret;
	DEEPTYPE_DISCORD_WEBHOOK: SecretsStoreSecret;
	DEEPTYPE_GA4_API_SECRET: SecretsStoreSecret;
	ACCOUNTS_PUBLIC_ORIGIN: string;
	ACCOUNTS_ALLOWED_HOSTNAMES: string;
	ACCOUNTS_FIRST_PARTY_CLIENT_IDS: string;
	ACCOUNTS_EMAIL_FROM: string;
	ACCOUNTS_EMAIL_REPLY_TO: string;
	ACCOUNTS_GOOGLE_CLIENT_ID: string;
	ACCOUNTS_KAKAO_CLIENT_ID: string;
	ACCOUNTS_BBATON_CLIENT_ID: string;
	STELLA_ALLOWED_HOSTNAMES: string;
	STELLA_PUBLIC_ORIGIN: string;
	STELLA_ACCOUNTS_ISSUER: string;
	STELLA_OIDC_CLIENT_ID: string;
	STELLA_EMAIL_FROM: string;
	STELLA_EMAIL_REPLY_TO: string;
	DEEPTYPE_PAY_PROFILE: string;
	DEEPTYPE_PUBLIC_ORIGIN: string;
	DEEPTYPE_EMAIL_FROM: string;
	DEEPTYPE_EMAIL_REPLY_TO: string;
	DEEPTYPE_REPORT_MODEL: string;
	DEEPTYPE_GA4_MEASUREMENT_ID: string;
	STELLA_PAYMENTS: Service /* entrypoint StellaPayments from payments-stg */ | Service /* entrypoint StellaPayments from payments */;
	VIBE_PAYMENTS: Service /* entrypoint VibePayments from payments-stg */ | Service /* entrypoint VibePayments from payments */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface StgEnv {
		HYPERDRIVE_FRESH: Hyperdrive;
		HYPERDRIVE_CACHED: Hyperdrive;
		ACCOUNTS_EMAIL_QUEUE: Queue;
		ACCOUNTS_AUTH_SECRET: SecretsStoreSecret;
		ACCOUNTS_IP_HASH_SALT: SecretsStoreSecret;
		ACCOUNTS_TURNSTILE_SECRET: SecretsStoreSecret;
		ACCOUNTS_GOOGLE_CLIENT_SECRET: SecretsStoreSecret;
		ACCOUNTS_KAKAO_CLIENT_SECRET: SecretsStoreSecret;
		ACCOUNTS_BBATON_CLIENT_SECRET: SecretsStoreSecret;
		ACCOUNTS_RESEND_API_KEY: SecretsStoreSecret;
		STELLA_TURNSTILE_SECRET: SecretsStoreSecret;
		STELLA_IP_HASH_SALT: SecretsStoreSecret;
		STELLA_DISCORD_WEBHOOK: SecretsStoreSecret;
		STELLA_RESEND_API_KEY: SecretsStoreSecret;
		STELLA_AUTH_SECRET: SecretsStoreSecret;
		STELLA_OIDC_CLIENT_SECRET: SecretsStoreSecret;
		DEEPTYPE_ANTHROPIC_API_KEY: SecretsStoreSecret;
		DEEPTYPE_RESEND_API_KEY: SecretsStoreSecret;
		DEEPTYPE_TURNSTILE_SECRET: SecretsStoreSecret;
		DEEPTYPE_DISCORD_WEBHOOK: SecretsStoreSecret;
		DEEPTYPE_GA4_API_SECRET: SecretsStoreSecret;
		ACCOUNTS_PUBLIC_ORIGIN: string;
		ACCOUNTS_ALLOWED_HOSTNAMES: string;
		ACCOUNTS_FIRST_PARTY_CLIENT_IDS: string;
		ACCOUNTS_EMAIL_FROM: string;
		ACCOUNTS_EMAIL_REPLY_TO: string;
		ACCOUNTS_GOOGLE_CLIENT_ID: string;
		ACCOUNTS_KAKAO_CLIENT_ID: string;
		ACCOUNTS_BBATON_CLIENT_ID: string;
		STELLA_ALLOWED_HOSTNAMES: string;
		STELLA_PUBLIC_ORIGIN: string;
		STELLA_ACCOUNTS_ISSUER: string;
		STELLA_OIDC_CLIENT_ID: string;
		STELLA_EMAIL_FROM: string;
		STELLA_EMAIL_REPLY_TO: string;
		DEEPTYPE_PAY_PROFILE: string;
		DEEPTYPE_PUBLIC_ORIGIN: string;
		DEEPTYPE_EMAIL_FROM: string;
		DEEPTYPE_EMAIL_REPLY_TO: string;
		DEEPTYPE_REPORT_MODEL: string;
		DEEPTYPE_GA4_MEASUREMENT_ID: string;
		STELLA_PAYMENTS: Service /* entrypoint StellaPayments from payments-stg */;
		VIBE_PAYMENTS: Service /* entrypoint VibePayments from payments-stg */;
	}
	interface Env extends __BaseEnv_DatabaseBindings {}
}
interface DatabaseBindings extends __BaseEnv_DatabaseBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACCOUNTS_PUBLIC_ORIGIN" | "ACCOUNTS_ALLOWED_HOSTNAMES" | "ACCOUNTS_FIRST_PARTY_CLIENT_IDS" | "ACCOUNTS_EMAIL_FROM" | "ACCOUNTS_EMAIL_REPLY_TO" | "ACCOUNTS_GOOGLE_CLIENT_ID" | "ACCOUNTS_KAKAO_CLIENT_ID" | "ACCOUNTS_BBATON_CLIENT_ID" | "STELLA_ALLOWED_HOSTNAMES" | "STELLA_PUBLIC_ORIGIN" | "STELLA_ACCOUNTS_ISSUER" | "STELLA_OIDC_CLIENT_ID" | "STELLA_EMAIL_FROM" | "STELLA_EMAIL_REPLY_TO" | "DEEPTYPE_PAY_PROFILE" | "DEEPTYPE_PUBLIC_ORIGIN" | "DEEPTYPE_EMAIL_FROM" | "DEEPTYPE_EMAIL_REPLY_TO" | "DEEPTYPE_REPORT_MODEL" | "DEEPTYPE_GA4_MEASUREMENT_ID">> {}
}
