/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=/dev/null --include-runtime=false --strict-vars=false --env-interface=StellaPublicBindings worker-configuration.generated.d.ts` (hash: e35b4e7c6d286f08bc2959c0ba798626)
interface __BaseEnv_StellaPublicBindings {
	ASSETS: Fetcher;
	DATABASE: Service /* entrypoint StellaService from database-stg */ | Service /* entrypoint StellaService from database */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface StgEnv {
		ASSETS: Fetcher;
		DATABASE: Service /* entrypoint StellaService from database-stg */;
	}
	interface Env extends __BaseEnv_StellaPublicBindings {}
}
interface StellaPublicBindings extends __BaseEnv_StellaPublicBindings {}
