/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=/dev/null --include-runtime=false --strict-vars=false --env-interface=VibePublicBindings worker-configuration.generated.d.ts` (hash: b43beb5af1917f33a98c9b5e5aa54ee1)
interface __BaseEnv_VibePublicBindings {
	ASSETS: Fetcher;
	DATABASE: Service /* entrypoint VibeService from database-stg */ | Service /* entrypoint VibeService from database */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface StgEnv {
		ASSETS: Fetcher;
		DATABASE: Service /* entrypoint VibeService from database-stg */;
	}
	interface Env extends __BaseEnv_VibePublicBindings {}
}
interface VibePublicBindings extends __BaseEnv_VibePublicBindings {}
