// Byte-identity fixture for the origin's proper nouns: short labels only, no prose. Any later stage that
// rewrites Korean text — a copy lint, a tone pass, an LLM polish — must return all 421 rows unchanged.
//
// Fidelity is NOT uniform, which is why `source` carries a prefix.
//   render:*    the string the DOM held after all 39 render() wrappers, confirmed by re-rendering the
//               origin's own screens and reading the nodes back.
//   markdown:*  WORLD_JOB_NAMES, from 12_256세계관직업_카탈로그_DeepType_v2_이름표.md, canonical per MIGRATION.md:14.
//               Canonical is not shipped, and not partly shipped either: zero of these 256 strings ever
//               reached the DOM. The assembler at :7745 overwrites every cell with a jobLeads+jobRoles
//               composition, so what users saw was formulaic. 103 of these names appear nowhere in the HTML
//               at all; jobRename (:7094, 138 entries) targets 83 more; the remaining 70 exist only inside
//               the dead `var WORLD_JOB_NAMES` literal at :4069. Freezing the hand-authored table is the
//               deliberate choice — this prefix marks which rows a DOM check cannot validate.
//
// Rows are (field, key, source, text), never bare strings: TALENT_ART one table away holds 16 values that
// are byte-equal to 16 strength names, so a bare-string set would merge rows and a failure would stop
// naming the table that broke. Single-string tables carry field 'value' to keep the shape uniform.
// COMBO keys are `{a}_{b}.{cell}` because the origin stores pairs as {a,b,n:{cell:name}} with no id.
//
// The failure mode is not hypothetical. The origin's report worker chained 85 `.replace` calls over LLM
// output; replaying that exact chain over this corpus mutates 8 rows:
//   markdown:WORLD_JOB_NAMES.INFJ_RAVU.value  먼길 방향잡이 -> 먼길 선택잡이
//   markdown:WORLD_JOB_NAMES.INFP_MAVU.value  무대 위 서사꾼 -> 무대 위 이야기꾼
//   markdown:WORLD_JOB_NAMES.INTP_MOHU.value  마음의 패턴연구가 -> 마음의 반복된 모습연구가
//   markdown:WORLD_JOB_NAMES.ESTJ_MOHU.value  사람 흐름 배치관 -> 사람 과정 배치관
//   render:WORLD_JOB_CORE.ROVU.strength  믿는 방향이 생기면 사람들과 함께 먼저 움직여요. -> 믿는 선택이 생기면 사람들과 함께 먼저 움직여요.
//   render:WORLD_JOB_CORE.RAVO.strength  내 공간과 시간을 지키며 편한 흐름을 만들어요. -> 내 공간과 시간을 지키며 편한 과정을 만들어요.
//   render:WORLD_JOB_FAMILY.INFJ.method  여러 말 속에서 중요한 뜻을 찾아 다음 방향을 정해요. -> 여러 말 속에서 중요한 뜻을 찾아 다음 선택을 정해요.
//   render:EVIDENCE_LABELS.align.value  방향을 맞춤 -> 선택을 맞춤
export const PROPER_NOUNS = [
  { field: 'value', key: 'ISTJ_ROVU', source: 'markdown:WORLD_JOB_NAMES', text: '봉화대 기록관' },
  { field: 'value', key: 'ISTJ_ROVO', source: 'markdown:WORLD_JOB_NAMES', text: '약속장부 서기관' },
  { field: 'value', key: 'ISTJ_ROHU', source: 'markdown:WORLD_JOB_NAMES', text: '붉은 잉크 검증관' },
  { field: 'value', key: 'ISTJ_ROHO', source: 'markdown:WORLD_JOB_NAMES', text: '시간의 서고지기' },
  { field: 'value', key: 'ISTJ_RAVU', source: 'markdown:WORLD_JOB_NAMES', text: '국경길 측량사' },
  { field: 'value', key: 'ISTJ_RAVO', source: 'markdown:WORLD_JOB_NAMES', text: '구름 항로 지도제작자' },
  { field: 'value', key: 'ISTJ_RAHU', source: 'markdown:WORLD_JOB_NAMES', text: '심야 교정관' },
  { field: 'value', key: 'ISTJ_RAHO', source: 'markdown:WORLD_JOB_NAMES', text: '철칙 보관관' },
  { field: 'value', key: 'ISTJ_MOVU', source: 'markdown:WORLD_JOB_NAMES', text: '광장 일정설계사' },
  { field: 'value', key: 'ISTJ_MOVO', source: 'markdown:WORLD_JOB_NAMES', text: '살림장부 정리사' },
  { field: 'value', key: 'ISTJ_MOHU', source: 'markdown:WORLD_JOB_NAMES', text: '사라진 이름 수집가' },
  { field: 'value', key: 'ISTJ_MOHO', source: 'markdown:WORLD_JOB_NAMES', text: '기억서랍 정리관' },
  { field: 'value', key: 'ISTJ_MAVU', source: 'markdown:WORLD_JOB_NAMES', text: '새 규칙 선포관' },
  { field: 'value', key: 'ISTJ_MAVO', source: 'markdown:WORLD_JOB_NAMES', text: '바람길 정리사' },
  { field: 'value', key: 'ISTJ_MAHU', source: 'markdown:WORLD_JOB_NAMES', text: '비밀 도면 완성자' },
  { field: 'value', key: 'ISTJ_MAHO', source: 'markdown:WORLD_JOB_NAMES', text: '고요 창고 관리관' },
  { field: 'value', key: 'ISFJ_ROVU', source: 'markdown:WORLD_JOB_NAMES', text: '선봉대 등불지기' },
  { field: 'value', key: 'ISFJ_ROVO', source: 'markdown:WORLD_JOB_NAMES', text: '온기집 살림지기' },
  { field: 'value', key: 'ISFJ_ROHU', source: 'markdown:WORLD_JOB_NAMES', text: '새벽 망루지기' },
  { field: 'value', key: 'ISFJ_ROHO', source: 'markdown:WORLD_JOB_NAMES', text: '기억의 성소지기' },
  { field: 'value', key: 'ISFJ_RAVU', source: 'markdown:WORLD_JOB_NAMES', text: '먼길 구호대장' },
  { field: 'value', key: 'ISFJ_RAVO', source: 'markdown:WORLD_JOB_NAMES', text: '떠돌이 쉼터지기' },
  { field: 'value', key: 'ISFJ_RAHU', source: 'markdown:WORLD_JOB_NAMES', text: '숨은 덫 감시관' },
  { field: 'value', key: 'ISFJ_RAHO', source: 'markdown:WORLD_JOB_NAMES', text: '마지막 방패지기' },
  { field: 'value', key: 'ISFJ_MOVU', source: 'markdown:WORLD_JOB_NAMES', text: '귀환 잔치 환대장' },
  { field: 'value', key: 'ISFJ_MOVO', source: 'markdown:WORLD_JOB_NAMES', text: '마음 쉼터지기' },
  { field: 'value', key: 'ISFJ_MOHU', source: 'markdown:WORLD_JOB_NAMES', text: '표정 읽는 동행인' },
  { field: 'value', key: 'ISFJ_MOHO', source: 'markdown:WORLD_JOB_NAMES', text: '작은 약속 보살피미' },
  { field: 'value', key: 'ISFJ_MAVU', source: 'markdown:WORLD_JOB_NAMES', text: '이동 찻집 주인' },
  { field: 'value', key: 'ISFJ_MAVO', source: 'markdown:WORLD_JOB_NAMES', text: '햇살 정원 돌봄가' },
  { field: 'value', key: 'ISFJ_MAHU', source: 'markdown:WORLD_JOB_NAMES', text: '별밤길 등불지기' },
  { field: 'value', key: 'ISFJ_MAHO', source: 'markdown:WORLD_JOB_NAMES', text: '마음방 문지기' },
  { field: 'value', key: 'INFJ_ROVU', source: 'markdown:WORLD_JOB_NAMES', text: '봉화길 안내자' },
  { field: 'value', key: 'INFJ_ROVO', source: 'markdown:WORLD_JOB_NAMES', text: '약속의 길잡이' },
  { field: 'value', key: 'INFJ_ROHU', source: 'markdown:WORLD_JOB_NAMES', text: '마음 밑길 해석가' },
  { field: 'value', key: 'INFJ_ROHO', source: 'markdown:WORLD_JOB_NAMES', text: '옛 등대지기' },
  { field: 'value', key: 'INFJ_RAVU', source: 'markdown:WORLD_JOB_NAMES', text: '먼길 방향잡이' },
  { field: 'value', key: 'INFJ_RAVO', source: 'markdown:WORLD_JOB_NAMES', text: '푸른길 항해사' },
  { field: 'value', key: 'INFJ_RAHU', source: 'markdown:WORLD_JOB_NAMES', text: '침묵의 별읽이' },
  { field: 'value', key: 'INFJ_RAHO', source: 'markdown:WORLD_JOB_NAMES', text: '북극성 파수꾼' },
  { field: 'value', key: 'INFJ_MOVU', source: 'markdown:WORLD_JOB_NAMES', text: '별빛 모임 안내자' },
  { field: 'value', key: 'INFJ_MOVO', source: 'markdown:WORLD_JOB_NAMES', text: '마음 다리 놓는이' },
  { field: 'value', key: 'INFJ_MOHU', source: 'markdown:WORLD_JOB_NAMES', text: '꿈의 뜻 읽는이' },
  { field: 'value', key: 'INFJ_MOHO', source: 'markdown:WORLD_JOB_NAMES', text: '속마음 길잡이' },
  { field: 'value', key: 'INFJ_MAVU', source: 'markdown:WORLD_JOB_NAMES', text: '새 길 이야기꾼' },
  { field: 'value', key: 'INFJ_MAVO', source: 'markdown:WORLD_JOB_NAMES', text: '바람 소식 전하는이' },
  { field: 'value', key: 'INFJ_MAHU', source: 'markdown:WORLD_JOB_NAMES', text: '내일지도 제작자' },
  { field: 'value', key: 'INFJ_MAHO', source: 'markdown:WORLD_JOB_NAMES', text: '흐린숲 안내자' },
  { field: 'value', key: 'INTJ_ROVU', source: 'markdown:WORLD_JOB_NAMES', text: '선봉 작전가' },
  { field: 'value', key: 'INTJ_ROVO', source: 'markdown:WORLD_JOB_NAMES', text: '성벽 살림설계사' },
  { field: 'value', key: 'INTJ_ROHU', source: 'markdown:WORLD_JOB_NAMES', text: '깊은 수읽기 전략가' },
  { field: 'value', key: 'INTJ_ROHO', source: 'markdown:WORLD_JOB_NAMES', text: '요새 판짜는이' },
  { field: 'value', key: 'INTJ_RAVU', source: 'markdown:WORLD_JOB_NAMES', text: '미지 항로 개척자' },
  { field: 'value', key: 'INTJ_RAVO', source: 'markdown:WORLD_JOB_NAMES', text: '독립 기지 건축가' },
  { field: 'value', key: 'INTJ_RAHU', source: 'markdown:WORLD_JOB_NAMES', text: '그림자 작전연구가' },
  { field: 'value', key: 'INTJ_RAHO', source: 'markdown:WORLD_JOB_NAMES', text: '철벽 계획관' },
  { field: 'value', key: 'INTJ_MOVU', source: 'markdown:WORLD_JOB_NAMES', text: '연합 전략 조율가' },
  { field: 'value', key: 'INTJ_MOVO', source: 'markdown:WORLD_JOB_NAMES', text: '안전망 짜는이' },
  { field: 'value', key: 'INTJ_MOHU', source: 'markdown:WORLD_JOB_NAMES', text: '마음길 지도사' },
  { field: 'value', key: 'INTJ_MOHO', source: 'markdown:WORLD_JOB_NAMES', text: '고요한 수싸움꾼' },
  { field: 'value', key: 'INTJ_MAVU', source: 'markdown:WORLD_JOB_NAMES', text: '판을 바꾸는 기획자' },
  { field: 'value', key: 'INTJ_MAVO', source: 'markdown:WORLD_JOB_NAMES', text: '유연한 길 설계사' },
  { field: 'value', key: 'INTJ_MAHU', source: 'markdown:WORLD_JOB_NAMES', text: '먼날 설계자' },
  { field: 'value', key: 'INTJ_MAHO', source: 'markdown:WORLD_JOB_NAMES', text: '안쪽 요새 설계자' },
  { field: 'value', key: 'ISTP_ROVU', source: 'markdown:WORLD_JOB_NAMES', text: '전선 장비해결사' },
  { field: 'value', key: 'ISTP_ROVO', source: 'markdown:WORLD_JOB_NAMES', text: '골목 공방 수선장' },
  { field: 'value', key: 'ISTP_ROHU', source: 'markdown:WORLD_JOB_NAMES', text: '무언 수리공' },
  { field: 'value', key: 'ISTP_ROHO', source: 'markdown:WORLD_JOB_NAMES', text: '대물림 도구지기' },
  { field: 'value', key: 'ISTP_RAVU', source: 'markdown:WORLD_JOB_NAMES', text: '들판 기계탐험가' },
  { field: 'value', key: 'ISTP_RAVO', source: 'markdown:WORLD_JOB_NAMES', text: '유랑 공방장' },
  { field: 'value', key: 'ISTP_RAHU', source: 'markdown:WORLD_JOB_NAMES', text: '검은 칼날 세공사' },
  { field: 'value', key: 'ISTP_RAHO', source: 'markdown:WORLD_JOB_NAMES', text: '철손 기술자' },
  { field: 'value', key: 'ISTP_MOVU', source: 'markdown:WORLD_JOB_NAMES', text: '파티 장비조련사' },
  { field: 'value', key: 'ISTP_MOVO', source: 'markdown:WORLD_JOB_NAMES', text: '살림도구 해결사' },
  { field: 'value', key: 'ISTP_MOHU', source: 'markdown:WORLD_JOB_NAMES', text: '고장 소리 듣는이' },
  { field: 'value', key: 'ISTP_MOHO', source: 'markdown:WORLD_JOB_NAMES', text: '섬세한 수선가' },
  { field: 'value', key: 'ISTP_MAVU', source: 'markdown:WORLD_JOB_NAMES', text: '무대 장치발명가' },
  { field: 'value', key: 'ISTP_MAVO', source: 'markdown:WORLD_JOB_NAMES', text: '가벼운 도구상인' },
  { field: 'value', key: 'ISTP_MAHU', source: 'markdown:WORLD_JOB_NAMES', text: '심야 장치연구가' },
  { field: 'value', key: 'ISTP_MAHO', source: 'markdown:WORLD_JOB_NAMES', text: '숨은 공방 기계지기' },
  { field: 'value', key: 'ISFP_ROVU', source: 'markdown:WORLD_JOB_NAMES', text: '불꽃 문양제작자' },
  { field: 'value', key: 'ISFP_ROVO', source: 'markdown:WORLD_JOB_NAMES', text: '모두의 색채공방장' },
  { field: 'value', key: 'ISFP_ROHU', source: 'markdown:WORLD_JOB_NAMES', text: '속빛 세공가' },
  { field: 'value', key: 'ISFP_ROHO', source: 'markdown:WORLD_JOB_NAMES', text: '손끝 유물복원가' },
  { field: 'value', key: 'ISFP_RAVU', source: 'markdown:WORLD_JOB_NAMES', text: '들꽃 의상여행가' },
  { field: 'value', key: 'ISFP_RAVO', source: 'markdown:WORLD_JOB_NAMES', text: '바람빛 공예가' },
  { field: 'value', key: 'ISFP_RAHU', source: 'markdown:WORLD_JOB_NAMES', text: '검은 유리조각가' },
  { field: 'value', key: 'ISFP_RAHO', source: 'markdown:WORLD_JOB_NAMES', text: '단단한 형태장인' },
  { field: 'value', key: 'ISFP_MOVU', source: 'markdown:WORLD_JOB_NAMES', text: '축제 빛연출가' },
  { field: 'value', key: 'ISFP_MOVO', source: 'markdown:WORLD_JOB_NAMES', text: '마음선물 제작자' },
  { field: 'value', key: 'ISFP_MOHU', source: 'markdown:WORLD_JOB_NAMES', text: '달빛 그림기록가' },
  { field: 'value', key: 'ISFP_MOHO', source: 'markdown:WORLD_JOB_NAMES', text: '여린결 무늬장인' },
  { field: 'value', key: 'ISFP_MAVU', source: 'markdown:WORLD_JOB_NAMES', text: '변신 의상연출가' },
  { field: 'value', key: 'ISFP_MAVO', source: 'markdown:WORLD_JOB_NAMES', text: '산들빛 소품가' },
  { field: 'value', key: 'ISFP_MAHU', source: 'markdown:WORLD_JOB_NAMES', text: '깊은밤 색채화가' },
  { field: 'value', key: 'ISFP_MAHO', source: 'markdown:WORLD_JOB_NAMES', text: '잿빛결 도예가' },
  { field: 'value', key: 'INFP_ROVU', source: 'markdown:WORLD_JOB_NAMES', text: '깃발 든 이야기꾼' },
  { field: 'value', key: 'INFP_ROVO', source: 'markdown:WORLD_JOB_NAMES', text: '고향 전설지기' },
  { field: 'value', key: 'INFP_ROHU', source: 'markdown:WORLD_JOB_NAMES', text: '속마음 기록자' },
  { field: 'value', key: 'INFP_ROHO', source: 'markdown:WORLD_JOB_NAMES', text: '약속의 책지기' },
  { field: 'value', key: 'INFP_RAVU', source: 'markdown:WORLD_JOB_NAMES', text: '먼길 시인' },
  { field: 'value', key: 'INFP_RAVO', source: 'markdown:WORLD_JOB_NAMES', text: '바람편지 배달인' },
  { field: 'value', key: 'INFP_RAHU', source: 'markdown:WORLD_JOB_NAMES', text: '검은잉크 작가' },
  { field: 'value', key: 'INFP_RAHO', source: 'markdown:WORLD_JOB_NAMES', text: '홀로 선 서약지기' },
  { field: 'value', key: 'INFP_MOVU', source: 'markdown:WORLD_JOB_NAMES', text: '희망극 이야기꾼' },
  { field: 'value', key: 'INFP_MOVO', source: 'markdown:WORLD_JOB_NAMES', text: '마음편지 작가' },
  { field: 'value', key: 'INFP_MOHU', source: 'markdown:WORLD_JOB_NAMES', text: '꿈조각 수집가' },
  { field: 'value', key: 'INFP_MOHO', source: 'markdown:WORLD_JOB_NAMES', text: '속삭임 보관자' },
  { field: 'value', key: 'INFP_MAVU', source: 'markdown:WORLD_JOB_NAMES', text: '무대 위 서사꾼' },
  { field: 'value', key: 'INFP_MAVO', source: 'markdown:WORLD_JOB_NAMES', text: '떠도는 노래지기' },
  { field: 'value', key: 'INFP_MAHU', source: 'markdown:WORLD_JOB_NAMES', text: '미완 세계 작가' },
  { field: 'value', key: 'INFP_MAHO', source: 'markdown:WORLD_JOB_NAMES', text: '고요책방 주인' },
  { field: 'value', key: 'INTP_ROVU', source: 'markdown:WORLD_JOB_NAMES', text: '원리 개척가' },
  { field: 'value', key: 'INTP_ROVO', source: 'markdown:WORLD_JOB_NAMES', text: '생활 지식 정비사' },
  { field: 'value', key: 'INTP_ROHU', source: 'markdown:WORLD_JOB_NAMES', text: '깊은 수수께끼 연구자' },
  { field: 'value', key: 'INTP_ROHO', source: 'markdown:WORLD_JOB_NAMES', text: '옛 법칙보관자' },
  { field: 'value', key: 'INTP_RAVU', source: 'markdown:WORLD_JOB_NAMES', text: '미지 현상추적자' },
  { field: 'value', key: 'INTP_RAVO', source: 'markdown:WORLD_JOB_NAMES', text: '자유실험 공방장' },
  { field: 'value', key: 'INTP_RAHU', source: 'markdown:WORLD_JOB_NAMES', text: '암호 해독가' },
  { field: 'value', key: 'INTP_RAHO', source: 'markdown:WORLD_JOB_NAMES', text: '단단한 논리설계자' },
  { field: 'value', key: 'INTP_MOVU', source: 'markdown:WORLD_JOB_NAMES', text: '질문광장 진행자' },
  { field: 'value', key: 'INTP_MOVO', source: 'markdown:WORLD_JOB_NAMES', text: '생활원리 설명가' },
  { field: 'value', key: 'INTP_MOHU', source: 'markdown:WORLD_JOB_NAMES', text: '마음의 패턴연구가' },
  { field: 'value', key: 'INTP_MOHO', source: 'markdown:WORLD_JOB_NAMES', text: '미완 가설 수집가' },
  { field: 'value', key: 'INTP_MAVU', source: 'markdown:WORLD_JOB_NAMES', text: '기발한 실험연출가' },
  { field: 'value', key: 'INTP_MAVO', source: 'markdown:WORLD_JOB_NAMES', text: '떠돌이 생각수리공' },
  { field: 'value', key: 'INTP_MAHU', source: 'markdown:WORLD_JOB_NAMES', text: '비밀 이론건축가' },
  { field: 'value', key: 'INTP_MAHO', source: 'markdown:WORLD_JOB_NAMES', text: '미로 속 진실찾는이' },
  { field: 'value', key: 'ESTP_ROVU', source: 'markdown:WORLD_JOB_NAMES', text: '선봉 돌파대장' },
  { field: 'value', key: 'ESTP_ROVO', source: 'markdown:WORLD_JOB_NAMES', text: '현장 구호대장' },
  { field: 'value', key: 'ESTP_ROHU', source: 'markdown:WORLD_JOB_NAMES', text: '무언 잠입해결사' },
  { field: 'value', key: 'ESTP_ROHO', source: 'markdown:WORLD_JOB_NAMES', text: '성문 최후수비수' },
  { field: 'value', key: 'ESTP_RAVU', source: 'markdown:WORLD_JOB_NAMES', text: '국경선 개척자' },
  { field: 'value', key: 'ESTP_RAVO', source: 'markdown:WORLD_JOB_NAMES', text: '자유항로 모험대장' },
  { field: 'value', key: 'ESTP_RAHU', source: 'markdown:WORLD_JOB_NAMES', text: '어둠길 추적자' },
  { field: 'value', key: 'ESTP_RAHO', source: 'markdown:WORLD_JOB_NAMES', text: '철벽 결투교관' },
  { field: 'value', key: 'ESTP_MOVU', source: 'markdown:WORLD_JOB_NAMES', text: '도전광장 진행자' },
  { field: 'value', key: 'ESTP_MOVO', source: 'markdown:WORLD_JOB_NAMES', text: '사람 구하는 현장대장' },
  { field: 'value', key: 'ESTP_MOHU', source: 'markdown:WORLD_JOB_NAMES', text: '위기 낌새잡이' },
  { field: 'value', key: 'ESTP_MOHO', source: 'markdown:WORLD_JOB_NAMES', text: '침착한 긴급구조원' },
  { field: 'value', key: 'ESTP_MAVU', source: 'markdown:WORLD_JOB_NAMES', text: '경기장 승부사' },
  { field: 'value', key: 'ESTP_MAVO', source: 'markdown:WORLD_JOB_NAMES', text: '바람길 곡예사' },
  { field: 'value', key: 'ESTP_MAHU', source: 'markdown:WORLD_JOB_NAMES', text: '비밀 임무 돌입자' },
  { field: 'value', key: 'ESTP_MAHO', source: 'markdown:WORLD_JOB_NAMES', text: '짙은숲 생존가' },
  { field: 'value', key: 'ESFP_ROVU', source: 'markdown:WORLD_JOB_NAMES', text: '환호의 축제대장' },
  { field: 'value', key: 'ESFP_ROVO', source: 'markdown:WORLD_JOB_NAMES', text: '귀환 잔치지기' },
  { field: 'value', key: 'ESFP_ROHU', source: 'markdown:WORLD_JOB_NAMES', text: '속마음 무대연출가' },
  { field: 'value', key: 'ESFP_ROHO', source: 'markdown:WORLD_JOB_NAMES', text: '추억 극장지기' },
  { field: 'value', key: 'ESFP_RAVU', source: 'markdown:WORLD_JOB_NAMES', text: '길 위 공연대장' },
  { field: 'value', key: 'ESFP_RAVO', source: 'markdown:WORLD_JOB_NAMES', text: '바닷바람 안내인' },
  { field: 'value', key: 'ESFP_RAHU', source: 'markdown:WORLD_JOB_NAMES', text: '집중무대 연출가' },
  { field: 'value', key: 'ESFP_RAHO', source: 'markdown:WORLD_JOB_NAMES', text: '중심무대 지휘자' },
  { field: 'value', key: 'ESFP_MOVU', source: 'markdown:WORLD_JOB_NAMES', text: '환호 수집가' },
  { field: 'value', key: 'ESFP_MOVO', source: 'markdown:WORLD_JOB_NAMES', text: '모두의 환대지기' },
  { field: 'value', key: 'ESFP_MOHU', source: 'markdown:WORLD_JOB_NAMES', text: '마음 울리는 배우' },
  { field: 'value', key: 'ESFP_MOHO', source: 'markdown:WORLD_JOB_NAMES', text: '객석 마음돌봄이' },
  { field: 'value', key: 'ESFP_MAVU', source: 'markdown:WORLD_JOB_NAMES', text: '변신 무대주인공' },
  { field: 'value', key: 'ESFP_MAVO', source: 'markdown:WORLD_JOB_NAMES', text: '산들축제 기획자' },
  { field: 'value', key: 'ESFP_MAHU', source: 'markdown:WORLD_JOB_NAMES', text: '새벽공연 창작자' },
  { field: 'value', key: 'ESFP_MAHO', source: 'markdown:WORLD_JOB_NAMES', text: '비밀극장 연출가' },
  { field: 'value', key: 'ENFP_ROVU', source: 'markdown:WORLD_JOB_NAMES', text: '인연길 개척자' },
  { field: 'value', key: 'ENFP_ROVO', source: 'markdown:WORLD_JOB_NAMES', text: '꿈동료 모으는이' },
  { field: 'value', key: 'ENFP_ROHU', source: 'markdown:WORLD_JOB_NAMES', text: '조용한 가능성발견가' },
  { field: 'value', key: 'ENFP_ROHO', source: 'markdown:WORLD_JOB_NAMES', text: '오래 가는 동료모집가' },
  { field: 'value', key: 'ENFP_RAVU', source: 'markdown:WORLD_JOB_NAMES', text: '세계길 탐험안내자' },
  { field: 'value', key: 'ENFP_RAVO', source: 'markdown:WORLD_JOB_NAMES', text: '자유마을 여행기획자' },
  { field: 'value', key: 'ENFP_RAHU', source: 'markdown:WORLD_JOB_NAMES', text: '아이디어 추적자' },
  { field: 'value', key: 'ENFP_RAHO', source: 'markdown:WORLD_JOB_NAMES', text: '자기길 응원대장' },
  { field: 'value', key: 'ENFP_MOVU', source: 'markdown:WORLD_JOB_NAMES', text: '영감축제 연결자' },
  { field: 'value', key: 'ENFP_MOVO', source: 'markdown:WORLD_JOB_NAMES', text: '마음동료 연결자' },
  { field: 'value', key: 'ENFP_MOHU', source: 'markdown:WORLD_JOB_NAMES', text: '꿈씨앗 발견가' },
  { field: 'value', key: 'ENFP_MOHO', source: 'markdown:WORLD_JOB_NAMES', text: '첫용기 북돋우미' },
  { field: 'value', key: 'ENFP_MAVU', source: 'markdown:WORLD_JOB_NAMES', text: '새세상 홍보대장' },
  { field: 'value', key: 'ENFP_MAVO', source: 'markdown:WORLD_JOB_NAMES', text: '떠돌이 만남기획자' },
  { field: 'value', key: 'ENFP_MAHU', source: 'markdown:WORLD_JOB_NAMES', text: '가능성 지도제작자' },
  { field: 'value', key: 'ENFP_MAHO', source: 'markdown:WORLD_JOB_NAMES', text: '닫힌문 여는이' },
  { field: 'value', key: 'ENTP_ROVU', source: 'markdown:WORLD_JOB_NAMES', text: '발명길 선도자' },
  { field: 'value', key: 'ENTP_ROVO', source: 'markdown:WORLD_JOB_NAMES', text: '생활문제 뒤집기꾼' },
  { field: 'value', key: 'ENTP_ROHU', source: 'markdown:WORLD_JOB_NAMES', text: '숨은 틈 공략가' },
  { field: 'value', key: 'ENTP_ROHO', source: 'markdown:WORLD_JOB_NAMES', text: '방어선 변형가' },
  { field: 'value', key: 'ENTP_RAVU', source: 'markdown:WORLD_JOB_NAMES', text: '경계 밖 실험개척자' },
  { field: 'value', key: 'ENTP_RAVO', source: 'markdown:WORLD_JOB_NAMES', text: '자유규칙 게임설계자' },
  { field: 'value', key: 'ENTP_RAHU', source: 'markdown:WORLD_JOB_NAMES', text: '반전 연구가' },
  { field: 'value', key: 'ENTP_RAHO', source: 'markdown:WORLD_JOB_NAMES', text: '흔들림 없는 논쟁가' },
  { field: 'value', key: 'ENTP_MOVU', source: 'markdown:WORLD_JOB_NAMES', text: '생각겨루기 진행자' },
  { field: 'value', key: 'ENTP_MOVO', source: 'markdown:WORLD_JOB_NAMES', text: '함께 푸는 발명가' },
  { field: 'value', key: 'ENTP_MOHU', source: 'markdown:WORLD_JOB_NAMES', text: '말밑뜻 발견가' },
  { field: 'value', key: 'ENTP_MOHO', source: 'markdown:WORLD_JOB_NAMES', text: '세밀한 변수수집가' },
  { field: 'value', key: 'ENTP_MAVU', source: 'markdown:WORLD_JOB_NAMES', text: '판을 바꾸는 연출가' },
  { field: 'value', key: 'ENTP_MAVO', source: 'markdown:WORLD_JOB_NAMES', text: '발상 장터상인' },
  { field: 'value', key: 'ENTP_MAHU', source: 'markdown:WORLD_JOB_NAMES', text: '비밀 세계발명가' },
  { field: 'value', key: 'ENTP_MAHO', source: 'markdown:WORLD_JOB_NAMES', text: '미로 안 반전설계자' },
  { field: 'value', key: 'ESTJ_ROVU', source: 'markdown:WORLD_JOB_NAMES', text: '전열 총괄대장' },
  { field: 'value', key: 'ESTJ_ROVO', source: 'markdown:WORLD_JOB_NAMES', text: '공동체 운영관' },
  { field: 'value', key: 'ESTJ_ROHU', source: 'markdown:WORLD_JOB_NAMES', text: '묵묵한 임무감독관' },
  { field: 'value', key: 'ESTJ_ROHO', source: 'markdown:WORLD_JOB_NAMES', text: '성문 질서대장' },
  { field: 'value', key: 'ESTJ_RAVU', source: 'markdown:WORLD_JOB_NAMES', text: '변경 개척사령관' },
  { field: 'value', key: 'ESTJ_RAVO', source: 'markdown:WORLD_JOB_NAMES', text: '독립거점 운영자' },
  { field: 'value', key: 'ESTJ_RAHU', source: 'markdown:WORLD_JOB_NAMES', text: '작전관리관' },
  { field: 'value', key: 'ESTJ_RAHO', source: 'markdown:WORLD_JOB_NAMES', text: '철칙 지휘관' },
  { field: 'value', key: 'ESTJ_MOVU', source: 'markdown:WORLD_JOB_NAMES', text: '연합길드 운영장' },
  { field: 'value', key: 'ESTJ_MOVO', source: 'markdown:WORLD_JOB_NAMES', text: '생활 문제 해결반장' },
  { field: 'value', key: 'ESTJ_MOHU', source: 'markdown:WORLD_JOB_NAMES', text: '사람 흐름 배치관' },
  { field: 'value', key: 'ESTJ_MOHO', source: 'markdown:WORLD_JOB_NAMES', text: '세심한 현장감독' },
  { field: 'value', key: 'ESTJ_MAVU', source: 'markdown:WORLD_JOB_NAMES', text: '대회 총괄기획자' },
  { field: 'value', key: 'ESTJ_MAVO', source: 'markdown:WORLD_JOB_NAMES', text: '이동시장 운영자' },
  { field: 'value', key: 'ESTJ_MAHU', source: 'markdown:WORLD_JOB_NAMES', text: '미래도시 건설관' },
  { field: 'value', key: 'ESTJ_MAHO', source: 'markdown:WORLD_JOB_NAMES', text: '숨은 기지 관리자' },
  { field: 'value', key: 'ESFJ_ROVU', source: 'markdown:WORLD_JOB_NAMES', text: '연합 응원대장' },
  { field: 'value', key: 'ESFJ_ROVO', source: 'markdown:WORLD_JOB_NAMES', text: '이웃 살림지킴이' },
  { field: 'value', key: 'ESFJ_ROHU', source: 'markdown:WORLD_JOB_NAMES', text: '속마음 중재관' },
  { field: 'value', key: 'ESFJ_ROHO', source: 'markdown:WORLD_JOB_NAMES', text: '약속 모임지기' },
  { field: 'value', key: 'ESFJ_RAVU', source: 'markdown:WORLD_JOB_NAMES', text: '길 위 지원단장' },
  { field: 'value', key: 'ESFJ_RAVO', source: 'markdown:WORLD_JOB_NAMES', text: '열린집 환대관' },
  { field: 'value', key: 'ESFJ_RAHU', source: 'markdown:WORLD_JOB_NAMES', text: '말없는 갈등조율사' },
  { field: 'value', key: 'ESFJ_RAHO', source: 'markdown:WORLD_JOB_NAMES', text: '믿음의 모임지기' },
  { field: 'value', key: 'ESFJ_MOVU', source: 'markdown:WORLD_JOB_NAMES', text: '축제 관계연결가' },
  { field: 'value', key: 'ESFJ_MOVO', source: 'markdown:WORLD_JOB_NAMES', text: '다정한 모임안내자' },
  { field: 'value', key: 'ESFJ_MOHU', source: 'markdown:WORLD_JOB_NAMES', text: '마음온도 읽는이' },
  { field: 'value', key: 'ESFJ_MOHO', source: 'markdown:WORLD_JOB_NAMES', text: '눈빛 살피는 돌봄관' },
  { field: 'value', key: 'ESFJ_MAVU', source: 'markdown:WORLD_JOB_NAMES', text: '만남무대 연출가' },
  { field: 'value', key: 'ESFJ_MAVO', source: 'markdown:WORLD_JOB_NAMES', text: '산들모임 기획자' },
  { field: 'value', key: 'ESFJ_MAHU', source: 'markdown:WORLD_JOB_NAMES', text: '새벽 편지 연결자' },
  { field: 'value', key: 'ESFJ_MAHO', source: 'markdown:WORLD_JOB_NAMES', text: '숨은마을 이웃지기' },
  { field: 'value', key: 'ENFJ_ROVU', source: 'markdown:WORLD_JOB_NAMES', text: '성장길 선도자' },
  { field: 'value', key: 'ENFJ_ROVO', source: 'markdown:WORLD_JOB_NAMES', text: '동료길 안내대장' },
  { field: 'value', key: 'ENFJ_ROHU', source: 'markdown:WORLD_JOB_NAMES', text: '숨은 용기 깨우는이' },
  { field: 'value', key: 'ENFJ_ROHO', source: 'markdown:WORLD_JOB_NAMES', text: '배움터 지킴이' },
  { field: 'value', key: 'ENFJ_RAVU', source: 'markdown:WORLD_JOB_NAMES', text: '새길 훈련대장' },
  { field: 'value', key: 'ENFJ_RAVO', source: 'markdown:WORLD_JOB_NAMES', text: '자유 배움 안내자' },
  { field: 'value', key: 'ENFJ_RAHU', source: 'markdown:WORLD_JOB_NAMES', text: '잠재력 발굴교관' },
  { field: 'value', key: 'ENFJ_RAHO', source: 'markdown:WORLD_JOB_NAMES', text: '중심 세우는 스승' },
  { field: 'value', key: 'ENFJ_MOVU', source: 'markdown:WORLD_JOB_NAMES', text: '함께 빛나는 길드장' },
  { field: 'value', key: 'ENFJ_MOVO', source: 'markdown:WORLD_JOB_NAMES', text: '손잡는 성장안내자' },
  { field: 'value', key: 'ENFJ_MOHU', source: 'markdown:WORLD_JOB_NAMES', text: '마음씨앗 키우는이' },
  { field: 'value', key: 'ENFJ_MOHO', source: 'markdown:WORLD_JOB_NAMES', text: '작은 용기 길잡이' },
  { field: 'value', key: 'ENFJ_MAVU', source: 'markdown:WORLD_JOB_NAMES', text: '꿈무대 훈련가' },
  { field: 'value', key: 'ENFJ_MAVO', source: 'markdown:WORLD_JOB_NAMES', text: '바람학교 여행교사' },
  { field: 'value', key: 'ENFJ_MAHU', source: 'markdown:WORLD_JOB_NAMES', text: '별빛 훈련관' },
  { field: 'value', key: 'ENFJ_MAHO', source: 'markdown:WORLD_JOB_NAMES', text: '흐린길 동행교관' },
  { field: 'value', key: 'ENTJ_ROVU', source: 'markdown:WORLD_JOB_NAMES', text: '원정 선봉사령관' },
  { field: 'value', key: 'ENTJ_ROVO', source: 'markdown:WORLD_JOB_NAMES', text: '연합도시 개척장' },
  { field: 'value', key: 'ENTJ_ROHU', source: 'markdown:WORLD_JOB_NAMES', text: '침묵의 승부전략가' },
  { field: 'value', key: 'ENTJ_ROHO', source: 'markdown:WORLD_JOB_NAMES', text: '철성 수호사령관' },
  { field: 'value', key: 'ENTJ_RAVU', source: 'markdown:WORLD_JOB_NAMES', text: '미지대륙 원정대장' },
  { field: 'value', key: 'ENTJ_RAVO', source: 'markdown:WORLD_JOB_NAMES', text: '독립항로 함대장' },
  { field: 'value', key: 'ENTJ_RAHU', source: 'markdown:WORLD_JOB_NAMES', text: '목표 추적지휘관' },
  { field: 'value', key: 'ENTJ_RAHO', source: 'markdown:WORLD_JOB_NAMES', text: '강철기지 총지휘관' },
  { field: 'value', key: 'ENTJ_MOVU', source: 'markdown:WORLD_JOB_NAMES', text: '대연합 길드장' },
  { field: 'value', key: 'ENTJ_MOVO', source: 'markdown:WORLD_JOB_NAMES', text: '사람을 모으는 지휘관' },
  { field: 'value', key: 'ENTJ_MOHU', source: 'markdown:WORLD_JOB_NAMES', text: '판세 읽는 원정대장' },
  { field: 'value', key: 'ENTJ_MOHO', source: 'markdown:WORLD_JOB_NAMES', text: '침착한 승리설계자' },
  { field: 'value', key: 'ENTJ_MAVU', source: 'markdown:WORLD_JOB_NAMES', text: '새시대 개척기획자' },
  { field: 'value', key: 'ENTJ_MAVO', source: 'markdown:WORLD_JOB_NAMES', text: '바람도시 건설대장' },
  { field: 'value', key: 'ENTJ_MAHU', source: 'markdown:WORLD_JOB_NAMES', text: '다음왕국 설계자' },
  { field: 'value', key: 'ENTJ_MAHO', source: 'markdown:WORLD_JOB_NAMES', text: '안개전선 총괄관' },
  { field: 'name', key: 'ROVU', source: 'render:WORLD_JOB_CORE', text: '함께 앞으로 가는 힘' },
  {
    field: 'strength',
    key: 'ROVU',
    source: 'render:WORLD_JOB_CORE',
    text: '믿는 방향이 생기면 사람들과 함께 먼저 움직여요.',
  },
  { field: 'name', key: 'ROVO', source: 'render:WORLD_JOB_CORE', text: '사람을 오래 챙기는 힘' },
  { field: 'strength', key: 'ROVO', source: 'render:WORLD_JOB_CORE', text: '가까운 사람과 한 약속을 오래 지켜요.' },
  { field: 'name', key: 'ROHU', source: 'render:WORLD_JOB_CORE', text: '마음먹은 일을 미는 힘' },
  { field: 'strength', key: 'ROHU', source: 'render:WORLD_JOB_CORE', text: '중요하다고 생각한 일은 쉽게 놓지 않아요.' },
  { field: 'name', key: 'ROHO', source: 'render:WORLD_JOB_CORE', text: '소중한 것을 지키는 힘' },
  { field: 'strength', key: 'ROHO', source: 'render:WORLD_JOB_CORE', text: '익숙한 관계와 생활을 차분히 이어가요.' },
  { field: 'name', key: 'RAVU', source: 'render:WORLD_JOB_CORE', text: '새 길을 여는 힘' },
  {
    field: 'strength',
    key: 'RAVU',
    source: 'render:WORLD_JOB_CORE',
    text: '스스로 판단하고 새로운 일을 먼저 시작해요.',
  },
  { field: 'name', key: 'RAVO', source: 'render:WORLD_JOB_CORE', text: '내 속도를 지키는 힘' },
  {
    field: 'strength',
    key: 'RAVO',
    source: 'render:WORLD_JOB_CORE',
    text: '내 공간과 시간을 지키며 편한 흐름을 만들어요.',
  },
  { field: 'name', key: 'RAHU', source: 'render:WORLD_JOB_CORE', text: '혼자 깊이 파는 힘' },
  {
    field: 'strength',
    key: 'RAHU',
    source: 'render:WORLD_JOB_CORE',
    text: '혼자 집중하면서 어려운 일도 끝까지 알아봐요.',
  },
  { field: 'name', key: 'RAHO', source: 'render:WORLD_JOB_CORE', text: '내 기준을 지키는 힘' },
  { field: 'strength', key: 'RAHO', source: 'render:WORLD_JOB_CORE', text: '스스로 정한 기준을 쉽게 바꾸지 않아요.' },
  { field: 'name', key: 'MOVU', source: 'render:WORLD_JOB_CORE', text: '함께 가능성을 키우는 힘' },
  {
    field: 'strength',
    key: 'MOVU',
    source: 'render:WORLD_JOB_CORE',
    text: '사람들과 생각을 주고받을수록 새로운 힘이 생겨요.',
  },
  { field: 'name', key: 'MOVO', source: 'render:WORLD_JOB_CORE', text: '먼저 다가가는 힘' },
  {
    field: 'strength',
    key: 'MOVO',
    source: 'render:WORLD_JOB_CORE',
    text: '주변 반응을 살피고 먼저 편하게 말을 걸어요.',
  },
  { field: 'name', key: 'MOHU', source: 'render:WORLD_JOB_CORE', text: '속마음을 오래 살피는 힘' },
  {
    field: 'strength',
    key: 'MOHU',
    source: 'render:WORLD_JOB_CORE',
    text: '말로 다 하지 않은 마음도 천천히 생각해요.',
  },
  { field: 'name', key: 'MOHO', source: 'render:WORLD_JOB_CORE', text: '작은 변화를 알아보는 힘' },
  { field: 'strength', key: 'MOHO', source: 'render:WORLD_JOB_CORE', text: '표정과 말투의 작은 변화를 놓치지 않아요.' },
  { field: 'name', key: 'MAVU', source: 'render:WORLD_JOB_CORE', text: '내 색을 보여주는 힘' },
  {
    field: 'strength',
    key: 'MAVU',
    source: 'render:WORLD_JOB_CORE',
    text: '나만의 생각과 모습을 밖으로 꺼내 보여줘요.',
  },
  { field: 'name', key: 'MAVO', source: 'render:WORLD_JOB_CORE', text: '부담 없이 시작하는 힘' },
  {
    field: 'strength',
    key: 'MAVO',
    source: 'render:WORLD_JOB_CORE',
    text: '내 속도를 지키면서 새로운 일을 가볍게 시작해요.',
  },
  { field: 'name', key: 'MAHU', source: 'render:WORLD_JOB_CORE', text: '큰 가능성을 키우는 힘' },
  {
    field: 'strength',
    key: 'MAHU',
    source: 'render:WORLD_JOB_CORE',
    text: '아직 보이지 않는 가능성을 혼자 오래 키워요.',
  },
  { field: 'name', key: 'MAHO', source: 'render:WORLD_JOB_CORE', text: '마음을 차분히 정리하는 힘' },
  {
    field: 'strength',
    key: 'MAHO',
    source: 'render:WORLD_JOB_CORE',
    text: '복잡한 마음을 혼자 정리하고 편한 자리를 찾아요.',
  },
  { field: 'name', key: 'ISTJ', source: 'render:WORLD_JOB_FAMILY', text: '꼼꼼한 기록관' },
  {
    field: 'method',
    key: 'ISTJ',
    source: 'render:WORLD_JOB_FAMILY',
    text: '해야 할 일을 정리하고 빠진 것이 없는지 확인해요.',
  },
  { field: 'role', key: 'ISTJ', source: 'render:WORLD_JOB_FAMILY', text: '기록하기 · 확인하기 · 지키기' },
  { field: 'name', key: 'ISFJ', source: 'render:WORLD_JOB_FAMILY', text: '세심한 수호자' },
  {
    field: 'method',
    key: 'ISFJ',
    source: 'render:WORLD_JOB_FAMILY',
    text: '작은 변화를 알아보고 사람과 약속을 잘 챙겨요.',
  },
  { field: 'role', key: 'ISFJ', source: 'render:WORLD_JOB_FAMILY', text: '지키기 · 살피기 · 돕기' },
  { field: 'name', key: 'INFJ', source: 'render:WORLD_JOB_FAMILY', text: '마음을 읽는 길잡이' },
  {
    field: 'method',
    key: 'INFJ',
    source: 'render:WORLD_JOB_FAMILY',
    text: '여러 말 속에서 중요한 뜻을 찾아 다음 방향을 정해요.',
  },
  { field: 'role', key: 'INFJ', source: 'render:WORLD_JOB_FAMILY', text: '뜻 찾기 · 마음 읽기 · 길잡기' },
  { field: 'name', key: 'INTJ', source: 'render:WORLD_JOB_FAMILY', text: '앞날을 그리는 설계자' },
  {
    field: 'method',
    key: 'INTJ',
    source: 'render:WORLD_JOB_FAMILY',
    text: '목표에 닿기 위한 순서와 방법을 먼저 짜요.',
  },
  { field: 'role', key: 'INTJ', source: 'render:WORLD_JOB_FAMILY', text: '계획 짜기 · 순서 잡기 · 멀리 보기' },
  { field: 'name', key: 'ISTP', source: 'render:WORLD_JOB_FAMILY', text: '현장의 기술자' },
  { field: 'method', key: 'ISTP', source: 'render:WORLD_JOB_FAMILY', text: '직접 만지고 해보면서 막힌 문제를 풀어요.' },
  { field: 'role', key: 'ISTP', source: 'render:WORLD_JOB_FAMILY', text: '뜯어보기 · 고치기 · 바로 움직이기' },
  { field: 'name', key: 'ISFP', source: 'render:WORLD_JOB_FAMILY', text: '감각을 담는 예술가' },
  {
    field: 'method',
    key: 'ISFP',
    source: 'render:WORLD_JOB_FAMILY',
    text: '눈과 손으로 느낀 것을 자기만의 모습으로 만들어요.',
  },
  { field: 'role', key: 'ISFP', source: 'render:WORLD_JOB_FAMILY', text: '느끼기 · 만들기 · 보여주기' },
  { field: 'name', key: 'INFP', source: 'render:WORLD_JOB_FAMILY', text: '마음을 쓰는 이야기 작가' },
  {
    field: 'method',
    key: 'INFP',
    source: 'render:WORLD_JOB_FAMILY',
    text: '중요하게 여기는 마음을 글과 이야기로 남겨요.',
  },
  { field: 'role', key: 'INFP', source: 'render:WORLD_JOB_FAMILY', text: '소중한 것 · 이야기 · 마음 전하기' },
  { field: 'name', key: 'INTP', source: 'render:WORLD_JOB_FAMILY', text: '원리를 찾는 연구자' },
  {
    field: 'method',
    key: 'INTP',
    source: 'render:WORLD_JOB_FAMILY',
    text: '왜 그런지 계속 묻고 숨어 있는 규칙을 찾아요.',
  },
  { field: 'role', key: 'INTP', source: 'render:WORLD_JOB_FAMILY', text: '이유 찾기 · 묻기 · 시험하기' },
  { field: 'name', key: 'ESTP', source: 'render:WORLD_JOB_FAMILY', text: '먼저 움직이는 해결사' },
  { field: 'method', key: 'ESTP', source: 'render:WORLD_JOB_FAMILY', text: '먼저 움직이고 부딪쳐 보면서 답을 찾아요.' },
  { field: 'role', key: 'ESTP', source: 'render:WORLD_JOB_FAMILY', text: '먼저 하기 · 위기 풀기 · 도전하기' },
  { field: 'name', key: 'ESFP', source: 'render:WORLD_JOB_FAMILY', text: '분위기를 살리는 연출자' },
  {
    field: 'method',
    key: 'ESFP',
    source: 'render:WORLD_JOB_FAMILY',
    text: '사람들의 반응을 보고 즐거운 분위기를 만들어요.',
  },
  { field: 'role', key: 'ESFP', source: 'render:WORLD_JOB_FAMILY', text: '즐기기 · 맞이하기 · 분위기 띄우기' },
  { field: 'name', key: 'ENFP', source: 'render:WORLD_JOB_FAMILY', text: '가능성을 찾는 탐험가' },
  {
    field: 'method',
    key: 'ENFP',
    source: 'render:WORLD_JOB_FAMILY',
    text: '사람과 생각을 이어 새로운 가능성을 찾아요.',
  },
  { field: 'role', key: 'ENFP', source: 'render:WORLD_JOB_FAMILY', text: '찾기 · 잇기 · 시작하기' },
  { field: 'name', key: 'ENTP', source: 'render:WORLD_JOB_FAMILY', text: '새 방법을 만드는 발명가' },
  {
    field: 'method',
    key: 'ENTP',
    source: 'render:WORLD_JOB_FAMILY',
    text: '익숙한 방법을 다르게 보고 더 나은 방법을 만들어요.',
  },
  { field: 'role', key: 'ENTP', source: 'render:WORLD_JOB_FAMILY', text: '생각 내기 · 뒤집기 · 규칙 만들기' },
  { field: 'name', key: 'ESTJ', source: 'render:WORLD_JOB_FAMILY', text: '일을 끝내는 현장 대장' },
  {
    field: 'method',
    key: 'ESTJ',
    source: 'render:WORLD_JOB_FAMILY',
    text: '사람과 할 일을 나눠 목표한 결과를 끝까지 만들어요.',
  },
  { field: 'role', key: 'ESTJ', source: 'render:WORLD_JOB_FAMILY', text: '실행하기 · 나누기 · 기준 세우기' },
  { field: 'name', key: 'ESFJ', source: 'render:WORLD_JOB_FAMILY', text: '사람을 잇는 모임 진행자' },
  {
    field: 'method',
    key: 'ESFJ',
    source: 'render:WORLD_JOB_FAMILY',
    text: '주변 사람을 살피고 모두가 함께 움직이게 도와요.',
  },
  { field: 'role', key: 'ESFJ', source: 'render:WORLD_JOB_FAMILY', text: '사람 잇기 · 챙기기 · 함께하기' },
  { field: 'name', key: 'ENFJ', source: 'render:WORLD_JOB_FAMILY', text: '성장을 돕는 안내자' },
  {
    field: 'method',
    key: 'ENFJ',
    source: 'render:WORLD_JOB_FAMILY',
    text: '사람의 장점을 알아보고 한 걸음 더 나아가게 도와요.',
  },
  { field: 'role', key: 'ENFJ', source: 'render:WORLD_JOB_FAMILY', text: '힘 북돋기 · 키우기 · 모으기' },
  { field: 'name', key: 'ENTJ', source: 'render:WORLD_JOB_FAMILY', text: '큰 목표를 이끄는 원정대장' },
  {
    field: 'method',
    key: 'ENTJ',
    source: 'render:WORLD_JOB_FAMILY',
    text: '큰 목표를 세우고 사람과 일을 모아 앞으로 이끌어요.',
  },
  { field: 'role', key: 'ENTJ', source: 'render:WORLD_JOB_FAMILY', text: '목표 세우기 · 준비 모으기 · 새길 열기' },
  { field: 'value', key: 'EI.E', source: 'render:ABILITY', text: '먼저 말을 거는 힘' },
  { field: 'value', key: 'EI.I', source: 'render:ABILITY', text: '혼자 오래 생각하는 힘' },
  { field: 'value', key: 'SN.S', source: 'render:ABILITY', text: '사실을 놓치지 않는 눈' },
  { field: 'value', key: 'SN.N', source: 'render:ABILITY', text: '가능성을 보는 눈' },
  { field: 'value', key: 'TF.T', source: 'render:ABILITY', text: '원인과 순서를 찾는 힘' },
  { field: 'value', key: 'TF.F', source: 'render:ABILITY', text: '상대 마음을 살피는 힘' },
  { field: 'value', key: 'JP.J', source: 'render:ABILITY', text: '일을 순서대로 정리하는 힘' },
  { field: 'value', key: 'JP.P', source: 'render:ABILITY', text: '갑자기 바뀌어도 움직이는 힘' },
  { field: 'value', key: 'RM.R', source: 'render:ABILITY', text: '흔들리지 않는 중심' },
  { field: 'value', key: 'RM.M', source: 'render:ABILITY', text: '작은 반응을 알아채는 힘' },
  { field: 'value', key: 'OA.O', source: 'render:ABILITY', text: '가까워지는 용기' },
  { field: 'value', key: 'OA.A', source: 'render:ABILITY', text: '홀로 서는 힘' },
  { field: 'value', key: 'VH.V', source: 'render:ABILITY', text: '마음을 말로 전하는 힘' },
  { field: 'value', key: 'VH.H', source: 'render:ABILITY', text: '마음을 천천히 정리하는 힘' },
  { field: 'value', key: 'UO.U', source: 'render:ABILITY', text: '다음 목표로 가는 힘' },
  { field: 'value', key: 'UO.O', source: 'render:ABILITY', text: '지켜내는 힘' },
  { field: 'value', key: 'SN_TF.ST', source: 'render:COMBO', text: '사실부터 확인하는 힘' },
  { field: 'value', key: 'SN_TF.SF', source: 'render:COMBO', text: '곁을 살피는 눈' },
  { field: 'value', key: 'SN_TF.NT', source: 'render:COMBO', text: '상황을 읽는 눈' },
  { field: 'value', key: 'SN_TF.NF', source: 'render:COMBO', text: '사람의 이야기를 이해하는 힘' },
  { field: 'value', key: 'EI_JP.EJ', source: 'render:COMBO', text: '사람과 일을 이끄는 힘' },
  { field: 'value', key: 'EI_JP.EP', source: 'render:COMBO', text: '그 자리에서 방법을 찾는 힘' },
  { field: 'value', key: 'EI_JP.IJ', source: 'render:COMBO', text: '혼자 완성하는 힘' },
  { field: 'value', key: 'EI_JP.IP', source: 'render:COMBO', text: '궁금한 것을 끝까지 파는 힘' },
  { field: 'value', key: 'RM_UO.RU', source: 'render:COMBO', text: '스스로 시작하는 힘' },
  { field: 'value', key: 'RM_UO.RO', source: 'render:COMBO', text: '흔들리지 않는 뿌리' },
  { field: 'value', key: 'RM_UO.MU', source: 'render:COMBO', text: '칭찬을 받으면 더 힘내는 능력' },
  { field: 'value', key: 'RM_UO.MO', source: 'render:COMBO', text: '곁을 지키는 온기' },
  { field: 'value', key: 'OA_VH.OV', source: 'render:COMBO', text: '마음을 잇는 손' },
  { field: 'value', key: 'OA_VH.OH', source: 'render:COMBO', text: '말없이 곁에 있는 힘' },
  { field: 'value', key: 'OA_VH.AV', source: 'render:COMBO', text: '무거운 분위기를 가볍게 푸는 힘' },
  { field: 'value', key: 'OA_VH.AH', source: 'render:COMBO', text: '혼자 마음을 정리하는 힘' },
  { field: 'name', key: 'MAKE', source: 'render:SIGNAL_COPY_V47', text: '직접 만들고 고치는 일' },
  { field: 'name', key: 'ANALYZE', source: 'render:SIGNAL_COPY_V47', text: '이유와 원인을 찾는 일' },
  { field: 'name', key: 'CREATE', source: 'render:SIGNAL_COPY_V47', text: '새로운 글과 모습을 만드는 일' },
  { field: 'name', key: 'HELP', source: 'render:SIGNAL_COPY_V47', text: '막힌 사람을 돕는 일' },
  { field: 'name', key: 'LEAD', source: 'render:SIGNAL_COPY_V47', text: '사람과 일을 움직이는 일' },
  { field: 'name', key: 'ORDER', source: 'render:SIGNAL_COPY_V47', text: '순서와 기준을 세우는 일' },
  { field: 'name', key: 'AUT', source: 'render:SIGNAL_COPY_V47', text: '방법을 직접 고를 수 있음' },
  { field: 'name', key: 'MASTER', source: 'render:SIGNAL_COPY_V47', text: '배우고 나아지는 느낌' },
  { field: 'name', key: 'IMPACT', source: 'render:SIGNAL_COPY_V47', text: '내 결과가 어디에 쓰이는지 확인함' },
  { field: 'name', key: 'BELONG', source: 'render:SIGNAL_COPY_V47', text: '믿는 사람과 함께함' },
  { field: 'name', key: 'STABLE', source: 'render:SIGNAL_COPY_V47', text: '앞으로의 일정을 알 수 있는 생활' },
  { field: 'name', key: 'NOVEL', source: 'render:SIGNAL_COPY_V47', text: '새 문제와 다른 방법' },
  { field: 'name', key: 'BREAK', source: 'render:SIGNAL_COPY_V47', text: '집중이 자주 끊기는 날' },
  { field: 'name', key: 'VAGUE', source: 'render:SIGNAL_COPY_V47', text: '어디까지 해야 하는지 분명하지 않은 일' },
  { field: 'name', key: 'EMPTY', source: 'render:SIGNAL_COPY_V47', text: '결과가 어디에 쓰이는지 모르는 일' },
  { field: 'name', key: 'TENSION', source: 'render:SIGNAL_COPY_V47', text: '불편한 말이 오래 남는 관계' },
  { field: 'name', key: 'OVERLOAD', source: 'render:SIGNAL_COPY_V47', text: '일의 양과 마감이 겹치는 때' },
  { field: 'name', key: 'STUCK', source: 'render:SIGNAL_COPY_V47', text: '방법을 바꿀 수 없는 일' },
  { field: 'name', key: 'SOLVE', source: 'render:SIGNAL_COPY_V47', text: '막힌 문제를 풀어 결과를 바꿀 때' },
  { field: 'name', key: 'UNDERSTAND', source: 'render:SIGNAL_COPY_V47', text: '복잡한 이유를 끝까지 알아낼 때' },
  { field: 'name', key: 'EXPRESS', source: 'render:SIGNAL_COPY_V47', text: '생각을 글이나 그림으로 만들 때' },
  { field: 'name', key: 'CARE', source: 'render:SIGNAL_COPY_V47', text: '힘든 사람을 도와 다시 움직이게 할 때' },
  { field: 'name', key: 'MOVE', source: 'render:SIGNAL_COPY_V47', text: '사람과 일을 앞으로 움직이게 할 때' },
  { field: 'name', key: 'STEADY', source: 'render:SIGNAL_COPY_V47', text: '정한 기준을 꾸준히 지킬 때' },
  { field: 'name', key: 'FOCUS_ENV', source: 'render:SIGNAL_COPY_V47', text: '한 가지에 오래 집중할 시간' },
  { field: 'name', key: 'TOGETHER_ENV', source: 'render:SIGNAL_COPY_V47', text: '믿는 사람과 바로 이야기할 수 있음' },
  { field: 'name', key: 'FREEDOM_ENV', source: 'render:SIGNAL_COPY_V47', text: '순서와 방법을 직접 고를 수 있음' },
  { field: 'name', key: 'CLEAR_ENV', source: 'render:SIGNAL_COPY_V47', text: '역할과 끝나는 기준이 분명함' },
  { field: 'name', key: 'VARIETY_ENV', source: 'render:SIGNAL_COPY_V47', text: '새로운 문제나 역할을 만나는 일' },
  { field: 'name', key: 'VISIBLE_ENV', source: 'render:SIGNAL_COPY_V47', text: '내 일이 만든 결과를 직접 볼 수 있음' },
  { field: 'value', key: 'clarify', source: 'render:EVIDENCE_LABELS', text: '쉽게 설명함' },
  { field: 'value', key: 'structure', source: 'render:EVIDENCE_LABELS', text: '구조를 세움' },
  { field: 'value', key: 'reframe', source: 'render:EVIDENCE_LABELS', text: '다른 관점을 냄' },
  { field: 'value', key: 'idea', source: 'render:EVIDENCE_LABELS', text: '새 방법을 떠올림' },
  { field: 'value', key: 'mediate', source: 'render:EVIDENCE_LABELS', text: '대화를 풀어냄' },
  { field: 'value', key: 'empathy', source: 'render:EVIDENCE_LABELS', text: '마음을 살핌' },
  { field: 'value', key: 'follow_through', source: 'render:EVIDENCE_LABELS', text: '끝까지 챙김' },
  { field: 'value', key: 'detail', source: 'render:EVIDENCE_LABELS', text: '빠진 것을 봄' },
  { field: 'value', key: 'initiate', source: 'render:EVIDENCE_LABELS', text: '먼저 시작함' },
  { field: 'value', key: 'ownership', source: 'render:EVIDENCE_LABELS', text: '내 일처럼 움직임' },
  { field: 'value', key: 'notice', source: 'render:EVIDENCE_LABELS', text: '문제를 먼저 봄' },
  { field: 'value', key: 'risk_scan', source: 'render:EVIDENCE_LABELS', text: '위험을 살핌' },
  { field: 'value', key: 'learn', source: 'render:EVIDENCE_LABELS', text: '빠르게 배움' },
  { field: 'value', key: 'mastery', source: 'render:EVIDENCE_LABELS', text: '혼자 해냄' },
  { field: 'value', key: 'support', source: 'render:EVIDENCE_LABELS', text: '실제 도움을 줌' },
  { field: 'value', key: 'care', source: 'render:EVIDENCE_LABELS', text: '사람을 돌봄' },
  { field: 'value', key: 'prioritize', source: 'render:EVIDENCE_LABELS', text: '우선순위를 세움' },
  { field: 'value', key: 'experiment', source: 'render:EVIDENCE_LABELS', text: '작게 시험함' },
  { field: 'value', key: 'adapt', source: 'render:EVIDENCE_LABELS', text: '방법을 바꿈' },
  { field: 'value', key: 'align', source: 'render:EVIDENCE_LABELS', text: '방향을 맞춤' },
  { field: 'value', key: 'communicate', source: 'render:EVIDENCE_LABELS', text: '사람의 말을 모음' },
  { field: 'value', key: 'focus', source: 'render:EVIDENCE_LABELS', text: '깊게 집중함' },
  { field: 'value', key: 'investigate', source: 'render:EVIDENCE_LABELS', text: '원인을 찾음' },
] as const

export type ProperNoun = (typeof PROPER_NOUNS)[number]
export type ProperNounSource = ProperNoun['source']
