// The 256 world-job names are content, not a derivation: the shipped HTML assembled them at runtime by
// concatenating a core-code lead with an inner-code role noun, which produced 256 formulaic strings that read the
// same. The v2 name table is the hand-authored replacement and differs from that runtime output in all 256 cells,
// so it is the source of truth and the strings are frozen here verbatim rather than recomposed.
// Key = `${InnerCode}_${CoreCode}`; the pair is what the report engine holds, so a single flat map avoids the
// nested lookup the original needed only because it stored rows positionally against CORE_ORDER.
export const WORLD_JOB_NAMES = {
  ENFJ_MAHO: '흐린길 동행교관',
  ENFJ_MAHU: '별빛 훈련관',
  ENFJ_MAVO: '바람학교 여행교사',
  ENFJ_MAVU: '꿈무대 훈련가',
  ENFJ_MOHO: '작은 용기 길잡이',
  ENFJ_MOHU: '마음씨앗 키우는이',
  ENFJ_MOVO: '손잡는 성장안내자',
  ENFJ_MOVU: '함께 빛나는 길드장',
  ENFJ_RAHO: '중심 세우는 스승',
  ENFJ_RAHU: '잠재력 발굴교관',
  ENFJ_RAVO: '자유 배움 안내자',
  ENFJ_RAVU: '새길 훈련대장',
  ENFJ_ROHO: '배움터 지킴이',
  ENFJ_ROHU: '숨은 용기 깨우는이',
  ENFJ_ROVO: '동료길 안내대장',
  ENFJ_ROVU: '성장길 선도자',
  ENFP_MAHO: '닫힌문 여는이',
  ENFP_MAHU: '가능성 지도제작자',
  ENFP_MAVO: '떠돌이 만남기획자',
  ENFP_MAVU: '새세상 홍보대장',
  ENFP_MOHO: '첫용기 북돋우미',
  ENFP_MOHU: '꿈씨앗 발견가',
  ENFP_MOVO: '마음동료 연결자',
  ENFP_MOVU: '영감축제 연결자',
  ENFP_RAHO: '자기길 응원대장',
  ENFP_RAHU: '아이디어 추적자',
  ENFP_RAVO: '자유마을 여행기획자',
  ENFP_RAVU: '세계길 탐험안내자',
  ENFP_ROHO: '오래 가는 동료모집가',
  ENFP_ROHU: '조용한 가능성발견가',
  ENFP_ROVO: '꿈동료 모으는이',
  ENFP_ROVU: '인연길 개척자',
  ENTJ_MAHO: '안개전선 총괄관',
  ENTJ_MAHU: '다음왕국 설계자',
  ENTJ_MAVO: '바람도시 건설대장',
  ENTJ_MAVU: '새시대 개척기획자',
  ENTJ_MOHO: '침착한 승리설계자',
  ENTJ_MOHU: '판세 읽는 원정대장',
  ENTJ_MOVO: '사람을 모으는 지휘관',
  ENTJ_MOVU: '대연합 길드장',
  ENTJ_RAHO: '강철기지 총지휘관',
  ENTJ_RAHU: '목표 추적지휘관',
  ENTJ_RAVO: '독립항로 함대장',
  ENTJ_RAVU: '미지대륙 원정대장',
  ENTJ_ROHO: '철성 수호사령관',
  ENTJ_ROHU: '침묵의 승부전략가',
  ENTJ_ROVO: '연합도시 개척장',
  ENTJ_ROVU: '원정 선봉사령관',
  ENTP_MAHO: '미로 안 반전설계자',
  ENTP_MAHU: '비밀 세계발명가',
  ENTP_MAVO: '발상 장터상인',
  ENTP_MAVU: '판을 바꾸는 연출가',
  ENTP_MOHO: '세밀한 변수수집가',
  ENTP_MOHU: '말밑뜻 발견가',
  ENTP_MOVO: '함께 푸는 발명가',
  ENTP_MOVU: '생각겨루기 진행자',
  ENTP_RAHO: '흔들림 없는 논쟁가',
  ENTP_RAHU: '반전 연구가',
  ENTP_RAVO: '자유규칙 게임설계자',
  ENTP_RAVU: '경계 밖 실험개척자',
  ENTP_ROHO: '방어선 변형가',
  ENTP_ROHU: '숨은 틈 공략가',
  ENTP_ROVO: '생활문제 뒤집기꾼',
  ENTP_ROVU: '발명길 선도자',
  ESFJ_MAHO: '숨은마을 이웃지기',
  ESFJ_MAHU: '새벽 편지 연결자',
  ESFJ_MAVO: '산들모임 기획자',
  ESFJ_MAVU: '만남무대 연출가',
  ESFJ_MOHO: '눈빛 살피는 돌봄관',
  ESFJ_MOHU: '마음온도 읽는이',
  ESFJ_MOVO: '다정한 모임안내자',
  ESFJ_MOVU: '축제 관계연결가',
  ESFJ_RAHO: '믿음의 모임지기',
  ESFJ_RAHU: '말없는 갈등조율사',
  ESFJ_RAVO: '열린집 환대관',
  ESFJ_RAVU: '길 위 지원단장',
  ESFJ_ROHO: '약속 모임지기',
  ESFJ_ROHU: '속마음 중재관',
  ESFJ_ROVO: '이웃 살림지킴이',
  ESFJ_ROVU: '연합 응원대장',
  ESFP_MAHO: '비밀극장 연출가',
  ESFP_MAHU: '새벽공연 창작자',
  ESFP_MAVO: '산들축제 기획자',
  ESFP_MAVU: '변신 무대주인공',
  ESFP_MOHO: '객석 마음돌봄이',
  ESFP_MOHU: '마음 울리는 배우',
  ESFP_MOVO: '모두의 환대지기',
  ESFP_MOVU: '환호 수집가',
  ESFP_RAHO: '중심무대 지휘자',
  ESFP_RAHU: '집중무대 연출가',
  ESFP_RAVO: '바닷바람 안내인',
  ESFP_RAVU: '길 위 공연대장',
  ESFP_ROHO: '추억 극장지기',
  ESFP_ROHU: '속마음 무대연출가',
  ESFP_ROVO: '귀환 잔치지기',
  ESFP_ROVU: '환호의 축제대장',
  ESTJ_MAHO: '숨은 기지 관리자',
  ESTJ_MAHU: '미래도시 건설관',
  ESTJ_MAVO: '이동시장 운영자',
  ESTJ_MAVU: '대회 총괄기획자',
  ESTJ_MOHO: '세심한 현장감독',
  ESTJ_MOHU: '사람 흐름 배치관',
  ESTJ_MOVO: '생활 문제 해결반장',
  ESTJ_MOVU: '연합길드 운영장',
  ESTJ_RAHO: '철칙 지휘관',
  ESTJ_RAHU: '작전관리관',
  ESTJ_RAVO: '독립거점 운영자',
  ESTJ_RAVU: '변경 개척사령관',
  ESTJ_ROHO: '성문 질서대장',
  ESTJ_ROHU: '묵묵한 임무감독관',
  ESTJ_ROVO: '공동체 운영관',
  ESTJ_ROVU: '전열 총괄대장',
  ESTP_MAHO: '짙은숲 생존가',
  ESTP_MAHU: '비밀 임무 돌입자',
  ESTP_MAVO: '바람길 곡예사',
  ESTP_MAVU: '경기장 승부사',
  ESTP_MOHO: '침착한 긴급구조원',
  ESTP_MOHU: '위기 낌새잡이',
  ESTP_MOVO: '사람 구하는 현장대장',
  ESTP_MOVU: '도전광장 진행자',
  ESTP_RAHO: '철벽 결투교관',
  ESTP_RAHU: '어둠길 추적자',
  ESTP_RAVO: '자유항로 모험대장',
  ESTP_RAVU: '국경선 개척자',
  ESTP_ROHO: '성문 최후수비수',
  ESTP_ROHU: '무언 잠입해결사',
  ESTP_ROVO: '현장 구호대장',
  ESTP_ROVU: '선봉 돌파대장',
  INFJ_MAHO: '흐린숲 안내자',
  INFJ_MAHU: '내일지도 제작자',
  INFJ_MAVO: '바람 소식 전하는이',
  INFJ_MAVU: '새 길 이야기꾼',
  INFJ_MOHO: '속마음 길잡이',
  INFJ_MOHU: '꿈의 뜻 읽는이',
  INFJ_MOVO: '마음 다리 놓는이',
  INFJ_MOVU: '별빛 모임 안내자',
  INFJ_RAHO: '북극성 파수꾼',
  INFJ_RAHU: '침묵의 별읽이',
  INFJ_RAVO: '푸른길 항해사',
  INFJ_RAVU: '먼길 방향잡이',
  INFJ_ROHO: '옛 등대지기',
  INFJ_ROHU: '마음 밑길 해석가',
  INFJ_ROVO: '약속의 길잡이',
  INFJ_ROVU: '봉화길 안내자',
  INFP_MAHO: '고요책방 주인',
  INFP_MAHU: '미완 세계 작가',
  INFP_MAVO: '떠도는 노래지기',
  INFP_MAVU: '무대 위 서사꾼',
  INFP_MOHO: '속삭임 보관자',
  INFP_MOHU: '꿈조각 수집가',
  INFP_MOVO: '마음편지 작가',
  INFP_MOVU: '희망극 이야기꾼',
  INFP_RAHO: '홀로 선 서약지기',
  INFP_RAHU: '검은잉크 작가',
  INFP_RAVO: '바람편지 배달인',
  INFP_RAVU: '먼길 시인',
  INFP_ROHO: '약속의 책지기',
  INFP_ROHU: '속마음 기록자',
  INFP_ROVO: '고향 전설지기',
  INFP_ROVU: '깃발 든 이야기꾼',
  INTJ_MAHO: '안쪽 요새 설계자',
  INTJ_MAHU: '먼날 설계자',
  INTJ_MAVO: '유연한 길 설계사',
  INTJ_MAVU: '판을 바꾸는 기획자',
  INTJ_MOHO: '고요한 수싸움꾼',
  INTJ_MOHU: '마음길 지도사',
  INTJ_MOVO: '안전망 짜는이',
  INTJ_MOVU: '연합 전략 조율가',
  INTJ_RAHO: '철벽 계획관',
  INTJ_RAHU: '그림자 작전연구가',
  INTJ_RAVO: '독립 기지 건축가',
  INTJ_RAVU: '미지 항로 개척자',
  INTJ_ROHO: '요새 판짜는이',
  INTJ_ROHU: '깊은 수읽기 전략가',
  INTJ_ROVO: '성벽 살림설계사',
  INTJ_ROVU: '선봉 작전가',
  INTP_MAHO: '미로 속 진실찾는이',
  INTP_MAHU: '비밀 이론건축가',
  INTP_MAVO: '떠돌이 생각수리공',
  INTP_MAVU: '기발한 실험연출가',
  INTP_MOHO: '미완 가설 수집가',
  INTP_MOHU: '마음의 패턴연구가',
  INTP_MOVO: '생활원리 설명가',
  INTP_MOVU: '질문광장 진행자',
  INTP_RAHO: '단단한 논리설계자',
  INTP_RAHU: '암호 해독가',
  INTP_RAVO: '자유실험 공방장',
  INTP_RAVU: '미지 현상추적자',
  INTP_ROHO: '옛 법칙보관자',
  INTP_ROHU: '깊은 수수께끼 연구자',
  INTP_ROVO: '생활 지식 정비사',
  INTP_ROVU: '원리 개척가',
  ISFJ_MAHO: '마음방 문지기',
  ISFJ_MAHU: '별밤길 등불지기',
  ISFJ_MAVO: '햇살 정원 돌봄가',
  ISFJ_MAVU: '이동 찻집 주인',
  ISFJ_MOHO: '작은 약속 보살피미',
  ISFJ_MOHU: '표정 읽는 동행인',
  ISFJ_MOVO: '마음 쉼터지기',
  ISFJ_MOVU: '귀환 잔치 환대장',
  ISFJ_RAHO: '마지막 방패지기',
  ISFJ_RAHU: '숨은 덫 감시관',
  ISFJ_RAVO: '떠돌이 쉼터지기',
  ISFJ_RAVU: '먼길 구호대장',
  ISFJ_ROHO: '기억의 성소지기',
  ISFJ_ROHU: '새벽 망루지기',
  ISFJ_ROVO: '온기집 살림지기',
  ISFJ_ROVU: '선봉대 등불지기',
  ISFP_MAHO: '잿빛결 도예가',
  ISFP_MAHU: '깊은밤 색채화가',
  ISFP_MAVO: '산들빛 소품가',
  ISFP_MAVU: '변신 의상연출가',
  ISFP_MOHO: '여린결 무늬장인',
  ISFP_MOHU: '달빛 그림기록가',
  ISFP_MOVO: '마음선물 제작자',
  ISFP_MOVU: '축제 빛연출가',
  ISFP_RAHO: '단단한 형태장인',
  ISFP_RAHU: '검은 유리조각가',
  ISFP_RAVO: '바람빛 공예가',
  ISFP_RAVU: '들꽃 의상여행가',
  ISFP_ROHO: '손끝 유물복원가',
  ISFP_ROHU: '속빛 세공가',
  ISFP_ROVO: '모두의 색채공방장',
  ISFP_ROVU: '불꽃 문양제작자',
  ISTJ_MAHO: '고요 창고 관리관',
  ISTJ_MAHU: '비밀 도면 완성자',
  ISTJ_MAVO: '바람길 정리사',
  ISTJ_MAVU: '새 규칙 선포관',
  ISTJ_MOHO: '기억서랍 정리관',
  ISTJ_MOHU: '사라진 이름 수집가',
  ISTJ_MOVO: '살림장부 정리사',
  ISTJ_MOVU: '광장 일정설계사',
  ISTJ_RAHO: '철칙 보관관',
  ISTJ_RAHU: '심야 교정관',
  ISTJ_RAVO: '구름 항로 지도제작자',
  ISTJ_RAVU: '국경길 측량사',
  ISTJ_ROHO: '시간의 서고지기',
  ISTJ_ROHU: '붉은 잉크 검증관',
  ISTJ_ROVO: '약속장부 서기관',
  ISTJ_ROVU: '봉화대 기록관',
  ISTP_MAHO: '숨은 공방 기계지기',
  ISTP_MAHU: '심야 장치연구가',
  ISTP_MAVO: '가벼운 도구상인',
  ISTP_MAVU: '무대 장치발명가',
  ISTP_MOHO: '섬세한 수선가',
  ISTP_MOHU: '고장 소리 듣는이',
  ISTP_MOVO: '살림도구 해결사',
  ISTP_MOVU: '파티 장비조련사',
  ISTP_RAHO: '철손 기술자',
  ISTP_RAHU: '검은 칼날 세공사',
  ISTP_RAVO: '유랑 공방장',
  ISTP_RAVU: '들판 기계탐험가',
  ISTP_ROHO: '대물림 도구지기',
  ISTP_ROHU: '무언 수리공',
  ISTP_ROVO: '골목 공방 수선장',
  ISTP_ROVU: '전선 장비해결사',
} as const
