sonar.projectKey=sobok
sonar.organization=sobok2026

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=sobok
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file.
sonar.sources=apps/api,apps/cataloger,apps/proxy,apps/notifier,apps/web,packages,tools
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*.spec.ts,**/*.test.ts,**/*.test.tsx,**/__tests__/**,**/public/**,**/e2e/**,**/.next/**,**/.turbo/**,**/build/**,**/coverage/**,**/dist/**

# Test configuration
sonar.javascript.lcov.reportPaths=coverage/lcov.info
