import ms from 'ms'

export const POINT_CONSTANTS = {
  AD_CLICK_REWARD: 5,
  LIBRARY_EXPANSION_PRICE: 300,
  LIBRARY_EXPANSION_AMOUNT: 1,
  LIBRARY_MAX_EXPANSION: 30,
  HISTORY_EXPANSION_PRICE: 250,
  HISTORY_EXPANSION_AMOUNT: 100,
  HISTORY_MAX_EXPANSION: 5000,
  RATING_EXPANSION_PRICE: 250,
  RATING_EXPANSION_AMOUNT: 100,
  RATING_MAX_EXPANSION: 5000,
  BOOKMARK_EXPANSION_SMALL_PRICE: 200,
  BOOKMARK_EXPANSION_SMALL_AMOUNT: 100,
  BOOKMARK_EXPANSION_LARGE_PRICE: 800,
  BOOKMARK_EXPANSION_LARGE_AMOUNT: 500,
  BOOKMARK_MAX_EXPANSION: 5000,
  PINNED_LIBRARY_EXPANSION_PRICE: 200,
  PINNED_LIBRARY_EXPANSION_AMOUNT: 5,
  PINNED_LIBRARY_MAX_EXPANSION: 100,
  BADGE_PRICE: 500,
  THEME_PRICE: 300,
  AD_SLOT_COOLDOWN_MS: ms('1 minute'),
  DAILY_EARN_LIMIT_COUNT: 20,
  TOKEN_EXPIRY_MS: ms('10 minutes'),
} as const

export const TRANSACTION_TYPE = {
  AD_CLICK: 1,
  LIBRARY_EXPANSION: 2,
  HISTORY_EXPANSION: 3,
  RATING_EXPANSION: 4,
  BOOKMARK_EXPANSION_SMALL: 5,
  BOOKMARK_EXPANSION_LARGE: 6,
  BADGE_PURCHASE: 7,
  THEME_PURCHASE: 8,
  ROULETTE_BET: 9,
  ROULETTE_PAYOUT: 10,
  DONATION: 11,
  PINNED_LIBRARY_EXPANSION: 12,
  ADMIN_GRANT: 13,
} as const

export const EXPANSION_TYPE = {
  LIBRARY: 1,
  READING_HISTORY: 2,
  BOOKMARK: 3,
  RATING: 4,
  PINNED_LIBRARY: 5,
} as const

export const ITEM_TYPE = {
  BADGE: 1,
  THEME: 2,
} as const
