/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings worker-configuration.generated.d.ts` (hash: 7eed2ed21da5fa2a6510c9be7c0fb179)
interface __BaseEnv_CloudflareBindings {
	VIBE_PRODUCTION: Service /* entrypoint VibeMaintenance from database */;
	VIBE_STAGING: Service /* entrypoint VibeMaintenance from database-stg */;
	STELLA_PRODUCTION: Service /* entrypoint StellaMaintenance from database */;
	STELLA_STAGING: Service /* entrypoint StellaMaintenance from database-stg */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
