/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings worker-configuration.generated.d.ts` (hash: 1184eaf631a0e861fa23cd0f43bf98f3)
interface __BaseEnv_CloudflareBindings {
	VIBE_PRODUCTION: Service /* entrypoint VibeMaintenance from vibe */;
	VIBE_STAGING: Service /* entrypoint VibeMaintenance from vibe-stg */;
	STELLA_PRODUCTION: Service /* entrypoint StellaMaintenance from stella */;
	STELLA_STAGING: Service /* entrypoint StellaMaintenance from stella-stg */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
