// AUTO-GENERATED by scripts/gen-characters.mjs — do not edit. Run `bun run gen:characters`.
import type { Gender } from './types'

/** Art states every person character ships (see scripts/gen-characters.mjs REQUIRED_STATES). */
export type ArtState = 'base' | 'heart'

/** Character identities per gender (art is keyed separately by state, below). */
export const PERSON_ROSTER: Record<Gender, readonly string[]> = {
  f: ['girl-1', 'girl-2', 'girl-3', 'girl-4', 'girl-5', 'girl-6', 'girl-7', 'girl-8'],
  m: ['man-1', 'man-2', 'man-3', 'man-4', 'man-5'],
}

/** Sprite key per (character, state) → public/characters/<key>.webp. */
export const PERSON_ART: Record<string, Record<ArtState, string>> = {
  'girl-1': { base: 'girl-1-base', heart: 'girl-1-heart' },
  'girl-2': { base: 'girl-2-base', heart: 'girl-2-heart' },
  'girl-3': { base: 'girl-3-base', heart: 'girl-3-heart' },
  'girl-4': { base: 'girl-4-base', heart: 'girl-4-heart' },
  'girl-5': { base: 'girl-5-base', heart: 'girl-5-heart' },
  'girl-6': { base: 'girl-6-base', heart: 'girl-6-heart' },
  'girl-7': { base: 'girl-7-base', heart: 'girl-7-heart' },
  'girl-8': { base: 'girl-8-base', heart: 'girl-8-heart' },
  'man-1': { base: 'man-1-base', heart: 'man-1-heart' },
  'man-2': { base: 'man-2-base', heart: 'man-2-heart' },
  'man-3': { base: 'man-3-base', heart: 'man-3-heart' },
  'man-4': { base: 'man-4-base', heart: 'man-4-heart' },
  'man-5': { base: 'man-5-base', heart: 'man-5-heart' },
}
