import type { GuardianDailyTheme, GuardianDailyTone } from '../../worker/guardian/daily-contract'

export const GUARDIAN_DAILY_UI = {
  themes: {
    self: '나를 돌아보는 카드',
    love: '사랑 카드',
    work: '일 카드',
    choice: '선택 카드',
  } satisfies Record<GuardianDailyTheme, string>,
  loveVariationNote:
    '사랑 카드의 그림은 Orbit 55% · Nebula 30% · Eclipse 12% · Stella 3%의 비율로 정해져요. 그림에 따른 해석의 차이는 없고, 다시 뽑을 수는 없어요.',
  tone: {
    label: '내일은 어떤 말이 듣고 싶나요?',
    options: {
      comfort: { label: '다정한 위로', description: '마음을 편안하게 해주는 말' },
      honesty: { label: '솔직한 조언', description: '내 마음을 솔직하게 돌아보는 말' },
      action: { label: '구체적인 행동', description: '지금 해볼 수 있는 작은 실천' },
      possibility: { label: '새로운 가능성', description: '미처 생각하지 못한 다른 방법' },
    } satisfies Record<GuardianDailyTone, { label: string; description: string }>,
  },
  today: {
    eyebrow: '오늘 만나는 수호령',
    title: '오늘의 수호령',
    intro: '오늘 하루를 함께할 수호령을 만나 보세요.',
    cta: '내일의 수호령 미리 보기',
  },
  tomorrow: {
    eyebrow: '하루 먼저 만나는 수호령',
    title: '내일의 수호령',
    intro: '내일 나에게 들려줄 이야기를 하루 먼저 만나 보세요.',
  },
  card: {
    natalBasis: '내 태양 별자리 기준',
    collectiveBasisToday: '오늘 달이 머무는 별자리 기준',
    collectiveBasisTomorrow: '내일 달이 머무는 별자리 기준',
    action: '오늘 해볼 한 가지',
    tomorrowAction: '내일 해볼 한 가지',
    reflection: '잠깐 돌아보기',
    archived: '보관함에 담겼어요',
    accessUntil: (date: string) => `${date}까지 하루 먼저 볼 수 있어요`,
  },
  locked: {
    kicker: (theme: string) => `내일은 ${theme} · 자정이 지나면 무료 공개`,
    title: (theme: string) => `내일의 ${theme}가 이미 도착했어요`,
    body: '네 가지 주제의 카드를 나흘에 걸쳐 한 번씩 만나요. 순서는 사람마다 달라요. 듣고 싶은 말을 고르면 내일 카드를 먼저 볼 수 있고, 이용 기간에 만난 카드는 보관함에 남아요.',
    cta: '7일 동안 하루 먼저 보기 · ₩1,900',
    note: '한 번 결제 · 자동 갱신 없음 · 구매 시점부터 168시간',
    reopen: '구매한 7일권 다시 열기',
  },
  active: {
    kicker: (theme: string) => `내일은 ${theme}`,
    title: '내일은 어떤 말이 듣고 싶나요?',
    body: '듣고 싶은 말을 고르면 내일 카드가 정해져요. 한번 정해진 카드는 바뀌지 않고 보관함에 남아요.',
    cta: '이런 말이 담긴 내일 카드 열기',
  },
  claim: {
    title: '카드를 계정에 보관할까요?',
    body: '소복 계정에 보관하면 다른 브라우저에서도 지난 카드와 최근 카드의 요약을 볼 수 있어요.',
    cta: '소복 계정에 보관하기',
    saving: '보관하는 중…',
    saved: '계정에 보관했어요',
    error: '지금은 계정에 보관하지 못했어요. 잠시 뒤 다시 시도해 주세요.',
  },
  summary: {
    eyebrow: '최근에 만난 카드',
    title: '최근 카드를 돌아보면',
    count: (count: number) => `카드 ${count}장에 자주 나온 주제와 조언`,
    themes: {
      self: '최근에는 내 마음을 돌보라는 카드가 자주 나왔어요.',
      love: '최근에는 가까운 사람과의 관계를 돌아보라는 카드가 자주 나왔어요.',
      work: '최근에는 일하는 이유와 무리 없이 이어갈 방법을 생각해 보라는 카드가 자주 나왔어요.',
      choice: '최근에는 선택의 기준과 필요한 정보를 살펴보라는 카드가 자주 나왔어요.',
    } satisfies Record<GuardianDailyTheme, string>,
    tones: {
      comfort: '조금 쉬어 가도 괜찮다는 다정한 위로가 많이 담겨 있었어요.',
      honesty: '내 마음을 솔직하게 들여다보라는 조언이 많이 담겨 있었어요.',
      action: '지금 할 수 있는 작은 일부터 시작해 보라는 조언이 많이 담겨 있었어요.',
      possibility: '결론을 서두르지 말고 다른 가능성도 살펴보라는 조언이 많이 담겨 있었어요.',
    } satisfies Record<GuardianDailyTone, string>,
    account: '내 카드 보관함 보기',
  },
  states: {
    loading: '수호령 카드를 고르는 중…',
    error: '수호령 카드를 불러오지 못했어요. 잠시 뒤 다시 확인해 주세요.',
    retry: '다시 불러오기',
  },
  checkout: {
    eyebrow: '7일 동안 하루 먼저 보기',
    title: '내일의 수호령을 오늘 만나요',
    body: '결제한 시점부터 168시간 동안 내일의 수호령 카드를 하루 먼저 볼 수 있어요. 나를 돌아보는 이야기부터 사랑, 일, 선택에 관한 이야기까지 차례로 만나요. 이용권은 자동으로 갱신되지 않아요.',
    orderTitle: '주문 내용',
    productLabel: '상품',
    priceLabel: '결제 금액',
    vatIncluded: '부가세 포함',
    durationLabel: '이용 기간',
    durationValue: '구매 시점부터 168시간',
    renewalLabel: '갱신',
    renewalValue: '자동 갱신 없음',
    emailLabel: '구매할 때 사용할 이메일',
    emailPlaceholder: 'you@example.com',
    emailHint: '결제 영수증과 보관함 복구 링크를 보내드려요. 광고 메일은 보내지 않아요.',
    methodLabel: '결제수단',
    methodLabels: { tosspay: '토스페이', card: '신용·체크카드' },
    securityHint: '안전한 결제를 위해 보안 확인을 완료해 주세요.',
    consentTitle: '결제 전 확인',
    consentAge: '만 14세 이상입니다. 생년월일은 받지 않아요.',
    consentTerms: '이용약관과 청약철회·환불 정책을 확인하고 동의합니다.',
    consentPrivacy: '결제와 이용권 제공 및 카드 보관에 필요한 개인정보 수집·이용에 동의합니다.',
    consentWithdrawal:
      '내일 카드를 처음 열기 전에는 청약철회를 요청할 수 있고, 카드를 연 뒤에는 디지털 콘텐츠 제공이 시작되어 청약철회가 제한될 수 있다는 점에 동의합니다.',
    minorNotice: '미성년자가 법정대리인의 동의 없이 맺은 계약은 미성년자 본인이나 법정대리인이 취소할 수 있어요.',
    submit: '₩1,900 결제하고 7일권 시작하기',
    submitting: '결제창을 준비하고 있어요…',
    confirming: '결제 결과를 확인하고 있어요…',
    back: '내일의 운세로 돌아가기',
    reopen: '구매한 7일권 다시 열기',
    errors: {
      storage: '이 브라우저에서 이용권 정보를 저장할 수 없어요.',
      turnstile: '보안 확인이 만료됐어요. 다시 확인해 주세요.',
      rateLimited: '요청이 너무 많아요. 잠시 뒤 다시 시도해 주세요.',
      active: '이미 사용 중인 7일권이 있어요. 내일의 카드로 돌아가 주세요.',
      interrupted: '결제가 완료되지 않았어요. 결제수단을 확인하고 다시 시도해 주세요.',
      service: '결제를 준비하지 못했어요. 잠시 뒤 다시 시도해 주세요.',
      generic: '결제를 시작하지 못했어요. 잠시 뒤 다시 시도해 주세요.',
    },
  },
  reopen: {
    eyebrow: '구매한 이용권 찾기',
    title: '구매한 7일권 다시 열기',
    body: '구매할 때 사용한 이메일을 입력하면 보관함을 다시 여는 링크를 보내드려요. 링크는 한 번만 쓸 수 있어요.',
    emailLabel: '구매할 때 사용한 이메일',
    submit: '보관함 링크 받기',
    submitting: '메일을 준비하고 있어요…',
    accepted: '입력한 이메일로 구매한 내역이 있으면 보관함 링크를 보내드릴게요.',
    exchanging: '보관함을 열고 있어요…',
    account: '이 보관함은 소복 계정에 저장되어 있어요. 로그인한 뒤 다시 열어 주세요.',
    invalid: '링크가 만료됐거나 이미 사용됐어요. 새 링크를 요청해 주세요.',
    error: '보관함 링크를 보내지 못했어요. 잠시 뒤 다시 시도해 주세요.',
    back: '내일의 운세로 돌아가기',
  },
} as const
