import type { GuardianDailyTheme, GuardianDailyTone } from '../../worker/guardian/daily-contract'

export const GUARDIAN_DAILY_UI = {
  themes: {
    self: '나를 보는 카드',
    love: '사랑 카드',
    work: '일 카드',
    choice: '선택 카드',
  } satisfies Record<GuardianDailyTheme, string>,
  loveVariationNote: '그림 결은 Orbit 55% · Nebula 30% · Eclipse 12% · Stella 3%이며 해석 차이나 재추첨은 없어요.',
  tone: {
    label: '내일 어떤 목소리가 필요해요?',
    options: {
      comfort: { label: '다정한 위로', description: '마음이 안심할 수 있는 말' },
      honesty: { label: '솔직한 통찰', description: '이미 알고 있던 사실을 보는 말' },
      action: { label: '구체적인 행동', description: '바로 옮길 수 있는 작은 동작' },
      possibility: { label: '새로운 가능성', description: '닫힌 결론 밖의 다른 길' },
    } satisfies Record<GuardianDailyTone, { label: string; description: string }>,
  },
  today: {
    eyebrow: 'TODAY’S GUARDIAN',
    title: '오늘의 수호령',
    intro: '오늘의 별이 건넨 한 장이에요.',
    cta: '내일의 수호령 미리 보기',
  },
  tomorrow: {
    eyebrow: 'TOMORROW’S GUARDIAN',
    title: '내일의 수호령',
    intro: '내일의 흐름을 하루 먼저 준비해 보세요.',
  },
  card: {
    natalBasis: '내 태양 별자리 기준',
    collectiveBasisToday: '오늘 달 별자리 기준',
    collectiveBasisTomorrow: '내일 달 별자리 기준',
    action: '오늘 해볼 한 가지',
    tomorrowAction: '내일 해볼 한 가지',
    reflection: '마음에 남길 질문',
    archived: '보관함에 담겼어요',
    accessUntil: (date: string) => `${date}까지 하루 먼저 볼 수 있어요`,
  },
  locked: {
    kicker: (theme: string) => `내일은 ${theme} · 자정이 지나면 무료 공개`,
    title: (theme: string) => `내일의 ${theme}가 이미 도착했어요`,
    body: '네 가지 테마는 사용자마다 다른 순서로 나흘 동안 한 번씩 나타나요. 필요한 목소리를 고르고 지금 열어보세요. 7일 동안 만난 카드는 보관함에 남아요.',
    cta: '7일 동안 하루 먼저 보기 · ₩1,900',
    note: '한 번 결제 · 자동 갱신 없음 · 구매 시점부터 168시간',
    reopen: '구매한 7일권 다시 열기',
  },
  active: {
    kicker: (theme: string) => `내일은 ${theme}`,
    title: '어떤 목소리로 먼저 만날까요?',
    body: '목소리를 고르면 내일 카드가 한 장으로 확정되고 보관함에 남아요.',
    cta: '이 목소리로 내일 카드 열기',
  },
  claim: {
    title: '카드를 계정에 보관할까요?',
    body: '소복 계정에 보관하면 다른 브라우저에서도 지난 카드와 일주일의 흐름을 다시 볼 수 있어요.',
    cta: '소복 계정에 보관하기',
    saving: '보관하는 중…',
    saved: '계정에 보관했어요',
    error: '지금은 계정에 보관하지 못했어요. 잠시 뒤 다시 시도해 주세요.',
  },
  summary: {
    eyebrow: 'YOUR SEVEN DAYS',
    title: '최근 카드가 만든 흐름',
    count: (count: number) => `${count}장의 카드에서 반복된 테마와 목소리`,
    themes: {
      self: '최근에는 나의 마음과 리듬을 살피는 카드가 자주 나타났어요.',
      love: '최근에는 사랑과 관계의 온도를 살피는 카드가 자주 나타났어요.',
      work: '최근에는 일의 동력과 지속 가능한 리듬을 살피는 카드가 자주 나타났어요.',
      choice: '최근에는 선택의 기준과 확인할 단서를 살피는 카드가 자주 나타났어요.',
    } satisfies Record<GuardianDailyTheme, string>,
    tones: {
      comfort: '이번 흐름은 더 밀어붙이기보다 안심할 자리를 먼저 만들라고 이야기하고 있어요.',
      honesty: '이번 흐름은 듣기 좋은 답보다 이미 알고 있던 사실을 또렷하게 바라보라고 이야기하고 있어요.',
      action: '이번 흐름은 완벽한 계획을 기다리기보다 지금 가능한 첫 동작을 반복하라고 이야기하고 있어요.',
      possibility: '이번 흐름은 하나의 결론을 서두르지 말고 아직 보지 않은 가능성을 남겨 두라고 이야기하고 있어요.',
    } satisfies Record<GuardianDailyTone, string>,
    account: '내 카드 보관함 보기',
  },
  states: {
    loading: '수호령 카드를 고르는 중…',
    error: '수호령 카드를 불러오지 못했어요. 잠시 뒤 다시 확인해 주세요.',
    retry: '다시 불러오기',
  },
  checkout: {
    eyebrow: '7-DAY EARLY ACCESS',
    title: '내일의 수호령을 오늘 만나요',
    body: '결제한 순간부터 168시간 동안 자기이해·사랑·일·선택 카드가 돌아오는 내일의 흐름을 하루 먼저 볼 수 있어요. 자동으로 갱신되지 않습니다.',
    orderTitle: '주문 내용',
    productLabel: '상품',
    priceLabel: '결제 금액',
    vatIncluded: '부가세 포함',
    durationLabel: '이용 기간',
    durationValue: '구매 시점부터 168시간',
    renewalLabel: '갱신',
    renewalValue: '자동 갱신 없음',
    emailLabel: '구매 이메일',
    emailPlaceholder: 'you@example.com',
    emailHint: '결제 영수증과 보관함 복구 링크를 보내드려요. 광고 메일은 보내지 않아요.',
    methodLabel: '결제수단',
    methodLabels: { tosspay: '토스페이', card: '신용·체크카드' },
    securityHint: '안전한 결제를 위해 보안 확인을 완료해 주세요.',
    consentTitle: '결제 전 확인',
    consentAge: '만 14세 이상입니다. 생년월일은 받지 않아요.',
    consentTerms: '이용약관과 청약철회·환불 정책을 확인하고 동의합니다.',
    consentPrivacy: '결제와 이용권 제공 및 카드 보관에 필요한 개인정보 수집·이용에 동의합니다.',
    consentWithdrawal:
      '내일 카드를 처음 열기 전에는 청약철회를 요청할 수 있고, 카드를 연 뒤에는 디지털 콘텐츠 제공이 시작되어 청약철회가 제한될 수 있다는 점에 동의합니다.',
    minorNotice: '미성년자가 법정대리인의 동의 없이 맺은 계약은 미성년자 본인이나 법정대리인이 취소할 수 있어요.',
    submit: '₩1,900 결제하고 7일권 시작하기',
    submitting: '결제창을 준비하고 있어요…',
    confirming: '결제 결과를 확인하고 있어요…',
    back: '내일의 운세로 돌아가기',
    reopen: '구매한 7일권 다시 열기',
    errors: {
      storage: '이 브라우저에서 이용권 정보를 저장할 수 없어요.',
      turnstile: '보안 확인이 만료됐어요. 다시 확인해 주세요.',
      rateLimited: '요청이 너무 많아요. 잠시 뒤 다시 시도해 주세요.',
      active: '이미 사용 중인 7일권이 있어요. 내일의 카드로 돌아가 주세요.',
      interrupted: '결제가 완료되지 않았어요. 결제수단을 확인하고 다시 시도해 주세요.',
      service: '결제를 준비하지 못했어요. 잠시 뒤 다시 시도해 주세요.',
      generic: '결제를 시작하지 못했어요. 잠시 뒤 다시 시도해 주세요.',
    },
  },
  reopen: {
    eyebrow: 'RESTORE ACCESS',
    title: '구매한 7일권 다시 열기',
    body: '구매할 때 사용한 이메일로 한 번만 쓸 수 있는 보관함 링크를 보내드려요.',
    emailLabel: '구매 이메일',
    submit: '재열람 링크 받기',
    submitting: '메일을 준비하고 있어요…',
    accepted: '구매 내역이 있으면 곧 재열람 링크를 보내드릴게요.',
    exchanging: '보관함을 다시 연결하고 있어요…',
    account: '이 보관함은 소복 계정에 저장되어 있어요. 로그인한 뒤 다시 열어 주세요.',
    invalid: '링크가 만료됐거나 이미 사용됐어요. 새 링크를 요청해 주세요.',
    error: '재열람 요청을 처리하지 못했어요. 잠시 뒤 다시 시도해 주세요.',
    back: '내일의 운세로 돌아가기',
  },
} as const
