import { mkdir } from 'node:fs/promises'
import path, { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const EMOJI_TEST_URL = 'https://unicode.org/Public/emoji/latest/emoji-test.txt'
const PACKAGE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const OUTPUT_PATH = path.join(PACKAGE_ROOT, 'src/generated/emojis.ts')

async function main() {
  const response = await fetch(EMOJI_TEST_URL)

  if (!response.ok) {
    throw new Error(`Failed to download emoji data: ${response.status} ${response.statusText}`)
  }

  const source = await response.text()
  const version = source.match(/^# Version: (.+)$/m)?.[1] ?? 'unknown'
  const emojis = parseFullyQualifiedEmojis(source)

  if (emojis.length === 0) {
    throw new Error('No fully-qualified emoji entries were found')
  }

  const output = [
    '/* This file is generated by packages/domain/scripts/generateEmojiList.ts. Do not edit manually. */',
    `export const UNICODE_EMOJI_VERSION = ${JSON.stringify(version)}`,
    'export const EMOJI_LIST: readonly string[] = [',
    ...emojis.map((emoji) => `  ${JSON.stringify(emoji)},`),
    ']',
    '',
  ].join('\n')

  await mkdir(dirname(OUTPUT_PATH), { recursive: true })
  await Bun.write(OUTPUT_PATH, output)
  console.log(
    `Generated ${emojis.length} emojis from Unicode Emoji ${version} at ${path.relative(PACKAGE_ROOT, OUTPUT_PATH)}`,
  )
}

function parseFullyQualifiedEmojis(source: string): string[] {
  const emojis: string[] = []

  for (const line of source.split('\n')) {
    if (!line.includes('; fully-qualified')) {
      continue
    }

    const emoji = line.match(/#\s+(\S+)\s+E[0-9.]+\s+/)?.[1]
    if (emoji) {
      emojis.push(emoji)
    }
  }

  return emojis
}

await main()
