// 빈 구조 — ko가 canonical이고 이 로케일의 번역을 기다린다. 컴포저는
// 빈 문자열을 건너뛰므로 이 상태에서는 리딩이 렌더되지 않는다.
import type { Interpretations } from './types'

export const interpretations: Interpretations = {
  stars: {
    ziwei: {
      life: '',
      siblings: '',
      spouse: '',
      children: '',
      wealth: '',
      health: '',
      travel: '',
      friends: '',
      career: '',
      property: '',
      wellbeing: '',
      parents: '',
    },
    tianji: {
      life: '',
      siblings: '',
      spouse: '',
      children: '',
      wealth: '',
      health: '',
      travel: '',
      friends: '',
      career: '',
      property: '',
      wellbeing: '',
      parents: '',
    },
    taiyang: {
      life: '',
      siblings: '',
      spouse: '',
      children: '',
      wealth: '',
      health: '',
      travel: '',
      friends: '',
      career: '',
      property: '',
      wellbeing: '',
      parents: '',
    },
    wuqu: {
      life: '',
      siblings: '',
      spouse: '',
      children: '',
      wealth: '',
      health: '',
      travel: '',
      friends: '',
      career: '',
      property: '',
      wellbeing: '',
      parents: '',
    },
    tiantong: {
      life: '',
      siblings: '',
      spouse: '',
      children: '',
      wealth: '',
      health: '',
      travel: '',
      friends: '',
      career: '',
      property: '',
      wellbeing: '',
      parents: '',
    },
    lianzhen: {
      life: '',
      siblings: '',
      spouse: '',
      children: '',
      wealth: '',
      health: '',
      travel: '',
      friends: '',
      career: '',
      property: '',
      wellbeing: '',
      parents: '',
    },
    tianfu: {
      life: '',
      siblings: '',
      spouse: '',
      children: '',
      wealth: '',
      health: '',
      travel: '',
      friends: '',
      career: '',
      property: '',
      wellbeing: '',
      parents: '',
    },
    taiyin: {
      life: '',
      siblings: '',
      spouse: '',
      children: '',
      wealth: '',
      health: '',
      travel: '',
      friends: '',
      career: '',
      property: '',
      wellbeing: '',
      parents: '',
    },
    tanlang: {
      life: '',
      siblings: '',
      spouse: '',
      children: '',
      wealth: '',
      health: '',
      travel: '',
      friends: '',
      career: '',
      property: '',
      wellbeing: '',
      parents: '',
    },
    jumen: {
      life: '',
      siblings: '',
      spouse: '',
      children: '',
      wealth: '',
      health: '',
      travel: '',
      friends: '',
      career: '',
      property: '',
      wellbeing: '',
      parents: '',
    },
    tianxiang: {
      life: '',
      siblings: '',
      spouse: '',
      children: '',
      wealth: '',
      health: '',
      travel: '',
      friends: '',
      career: '',
      property: '',
      wellbeing: '',
      parents: '',
    },
    tianliang: {
      life: '',
      siblings: '',
      spouse: '',
      children: '',
      wealth: '',
      health: '',
      travel: '',
      friends: '',
      career: '',
      property: '',
      wellbeing: '',
      parents: '',
    },
    qisha: {
      life: '',
      siblings: '',
      spouse: '',
      children: '',
      wealth: '',
      health: '',
      travel: '',
      friends: '',
      career: '',
      property: '',
      wellbeing: '',
      parents: '',
    },
    pojun: {
      life: '',
      siblings: '',
      spouse: '',
      children: '',
      wealth: '',
      health: '',
      travel: '',
      friends: '',
      career: '',
      property: '',
      wellbeing: '',
      parents: '',
    },
  },
  mutagens: {
    lu: {
      lianzhen: '',
      tianji: '',
      tiantong: '',
      taiyin: '',
      tanlang: '',
      wuqu: '',
      taiyang: '',
      jumen: '',
      tianliang: '',
      pojun: '',
    },
    quan: {
      pojun: '',
      tianliang: '',
      tianji: '',
      tiantong: '',
      taiyin: '',
      tanlang: '',
      wuqu: '',
      taiyang: '',
      ziwei: '',
      jumen: '',
    },
    ke: {
      wuqu: '',
      ziwei: '',
      wenchang: '',
      tianji: '',
      youbi: '',
      tianliang: '',
      taiyin: '',
      wenqu: '',
      zuofu: '',
    },
    ji: {
      taiyang: '',
      taiyin: '',
      lianzhen: '',
      jumen: '',
      tianji: '',
      wenqu: '',
      tiantong: '',
      wenchang: '',
      wuqu: '',
      tanlang: '',
    },
  },
  emptyPalace: {
    life: '',
    siblings: '',
    spouse: '',
    children: '',
    wealth: '',
    health: '',
    travel: '',
    friends: '',
    career: '',
    property: '',
    wellbeing: '',
    parents: '',
  },
  patterns: {
    changquJiaming: '',
    fuxiangChaoyuan: '',
    huoTan: '',
    jiyueTongliang: '',
    junchenQinghui: '',
    kuiyueJiaming: '',
    lingTan: '',
    lumaJiaochi: '',
    qishaChaodou: '',
    riyueTonggong: '',
    rizhaoLeimen: '',
    sanqiJiahui: '',
    shapolang: '',
    shuangluChaoyuan: '',
    tanwuTongxing: '',
    yingxingRumiao: '',
    yuelangTianmen: '',
    zifuTonggong: '',
  },
  report: {
    title: '',
    subtitle: '',
    chapterTitles: {
      core: '',
      signature: '',
      love: '',
      work: '',
      money: '',
      people: '',
      family: '',
      mind: '',
      health: '',
      path: '',
      closing: '',
    },
    signatureIntro: '',
    kicker: {
      lifeStar: '',
      bodyPalace: '',
      mutagen: '',
      pattern: '',
      palaceStar: '',
      borrowed: '',
      decade: '',
      fiveElements: '',
      empty: '',
    },
    patternNames: {
      changquJiaming: '',
      fuxiangChaoyuan: '',
      huoTan: '',
      jiyueTongliang: '',
      junchenQinghui: '',
      kuiyueJiaming: '',
      lingTan: '',
      lumaJiaochi: '',
      qishaChaodou: '',
      riyueTonggong: '',
      rizhaoLeimen: '',
      sanqiJiahui: '',
      shapolang: '',
      shuangluChaoyuan: '',
      tanwuTongxing: '',
      yingxingRumiao: '',
      yuelangTianmen: '',
      zifuTonggong: '',
    },
    bodyPalace: {
      life: '',
      spouse: '',
      wealth: '',
      travel: '',
      career: '',
      wellbeing: '',
    },
    fiveElements: {
      water2: '',
      wood3: '',
      metal4: '',
      earth5: '',
      fire6: '',
    },
    brightness: {
      strong: '',
      weak: '',
    },
    companions: {
      lucky: '',
      unlucky: '',
    },
    mutagenNotes: {
      lu: '',
      quan: '',
      ke: '',
      ji: '',
    },
    core: {
      bridge: '',
    },
    borrowedNote: '',
    path: {
      intro: '',
      empty: '',
    },
    health: {
      disclaimer: '',
    },
    closing: {
      outro: '',
    },
  },
}
