/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.compute.jsonc --env-file=/dev/null --include-runtime=false --strict-vars=false --env-interface=CivilComputeBindings compute-configuration.generated.d.ts` (hash: 39c8a537732fe9b5dd076ca03702b9e7)
interface __BaseEnv_CivilComputeBindings {
	CIVIL_FILES: R2Bucket;
	CALCULATION_CONTAINER: DurableObjectNamespace<import("./compute/worker").CivilCalculationContainer>;
	ARTIFACT_CONTAINER: DurableObjectNamespace<import("./compute/worker").CivilArtifactContainer>;
	DATABASE: Service /* entrypoint CivilComputationService from database-stg */ | Service /* entrypoint CivilComputationService from database */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./compute/worker");
		durableNamespaces: "CivilCalculationContainer" | "CivilArtifactContainer";
	}
	interface StgEnv {
		CIVIL_FILES: R2Bucket;
		CALCULATION_CONTAINER: DurableObjectNamespace<import("./compute/worker").CivilCalculationContainer>;
		ARTIFACT_CONTAINER: DurableObjectNamespace<import("./compute/worker").CivilArtifactContainer>;
		DATABASE: Service /* entrypoint CivilComputationService from database-stg */;
	}
	interface Env extends __BaseEnv_CivilComputeBindings {}
}
interface CivilComputeBindings extends __BaseEnv_CivilComputeBindings {}
