/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.compute.jsonc --env-file=/dev/null --include-runtime=false --strict-vars=false --env-interface=CivilComputeBindings compute-configuration.generated.d.ts` (hash: 9e4d9cb6e07dafe5168de49a1dcb0042)
interface __BaseEnv_CivilComputeBindings {
	DATABASE: Service /* entrypoint CivilComputationService from database-stg */ | Service /* entrypoint CivilComputationService from database */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./compute/worker");
	}
	interface StgEnv {
		DATABASE: Service /* entrypoint CivilComputationService from database-stg */;
	}
	interface Env extends __BaseEnv_CivilComputeBindings {}
}
interface CivilComputeBindings extends __BaseEnv_CivilComputeBindings {}
