/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.compute.jsonc --env-file=/dev/null --include-runtime=false --strict-vars=false --env-interface=CivilComputeBindings compute-configuration.generated.d.ts` (hash: 50b9926020dde67b9d69a97a40b8964b)
interface __BaseEnv_CivilComputeBindings {
	CIVIL_FILES: R2Bucket;
	DATABASE: Service /* entrypoint CivilComputationService from database-stg */ | Service /* entrypoint CivilComputationService from database */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./compute/worker");
	}
	interface StgEnv {
		CIVIL_FILES: R2Bucket;
		DATABASE: Service /* entrypoint CivilComputationService from database-stg */;
	}
	interface Env extends __BaseEnv_CivilComputeBindings {}
}
interface CivilComputeBindings extends __BaseEnv_CivilComputeBindings {}
