/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=/dev/null --include-runtime=false --strict-vars=false --env-interface=CivilPublicBindings worker-configuration.generated.d.ts` (hash: 283a106bddd81f09c2b74ecf7246c83f)
interface __BaseEnv_CivilPublicBindings {
	ASSETS: Fetcher;
	DATABASE: Service /* entrypoint CivilService from database-stg */ | Service /* entrypoint CivilService from database */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface StgEnv {
		ASSETS: Fetcher;
		DATABASE: Service /* entrypoint CivilService from database-stg */;
	}
	interface Env extends __BaseEnv_CivilPublicBindings {}
}
interface CivilPublicBindings extends __BaseEnv_CivilPublicBindings {}
