import type { LibraryItemSort, RatingSort } from '@sobok/domain/library/sort'
import type { Locale } from '@sobok/domain/locale'
import { PostFilter } from '@sobok/domain/post/filter'

export const QueryKeys = {
  me: ['me'],
  followingUsers: ['me', 'users', 'following'],
  readingHistoryBase: ['me', 'readingHistory'],
  ratingsBase: ['me', 'ratings'],
  bookmarks: ['me', 'bookmarks'],
  likedPosts: ['me', 'posts', 'liked'],
  infiniteBookmarksBase: ['me', 'bookmarks', 'infinite'],
  infiniteBookmarks: (sort: LibraryItemSort, locale: string) => [...QueryKeys.infiniteBookmarksBase, sort, locale],
  infiniteReadingHistory: (source: 'local' | 'server', locale?: string) => [
    'me',
    'readingHistory',
    'infinite',
    source,
    locale,
  ],
  infiniteRatings: (sort: RatingSort, locale?: string) => ['me', 'ratings', 'infinite', sort, locale],
  censorship: ['me', 'censorships'],
  infiniteCensorships: ['me', 'censorships', 'infinite'],
  passkeys: ['me', 'passkeys'],
  notification: ['me', 'notifications'],
  notificationUnreadCount: ['me', 'notifications', 'unread-count'],
  notifications: (searchParams: URLSearchParams) => ['me', 'notifications', Object.fromEntries(searchParams)],
  libraries: ['me', 'libraries'],
  infiniteLibraryListBase: ['library', 'list', 'infinite'],
  infinitePublicLibraryMangasBase: ['library', 'manga', 'infinite'],
  infinitePublicLibraryMangas: (locale: string, userId?: number) => [
    ...QueryKeys.infinitePublicLibraryMangasBase,
    userId ?? 'guest',
    locale,
  ],
  librarySummaryBase: ['library', 'summary'],
  localReadingHistorySummary: ['library', 'history', 'local', 'summary'],
  infiniteLibraryList: (userId?: number) => [...QueryKeys.infiniteLibraryListBase, userId ?? 'guest'],
  infinitePinnedLibraryList: (userId?: number) => ['library', 'list', 'infinite', 'pinned', userId ?? 'guest'],
  librarySummary: (userId?: number) => ['library', 'summary', userId ?? 'guest'],
  libraryMeta: (libraryId: number, userId?: number) => ['library', 'meta', libraryId, userId ?? 'guest'],
  libraryItemsBase: (libraryId: number) => ['me', 'library', libraryId, 'items'],
  libraryItems: (libraryId: number, scope: 'me' | 'public', sort: LibraryItemSort, locale: string) => [
    ...QueryKeys.libraryItemsBase(libraryId),
    scope,
    sort,
    locale,
  ],
  userRating: (mangaId: number) => ['me', 'rating', mangaId],
  readingHistory: (mangaId: number) => ['me', 'readingHistory', mangaId],
  points: ['me', 'points'],
  pointsExpansion: ['me', 'points', 'expansion'],
  pointsTurnstile: ['me', 'points', 'turnstile'],
  pointsTransactionsBase: ['me', 'points', 'transactions'],
  pointsTransactions: (locale: string) => [...QueryKeys.pointsTransactionsBase, locale],
  pointsToken: (adSlotId: string) => ['me', 'points', 'token', adSlotId],
  myDonationsBase: ['me', 'donations'],
  myDonations: (locale: string) => [...QueryKeys.myDonationsBase, locale],

  adsterraStats: (startDate: string, finishDate: string) => ['adsterra', 'stats', startDate, finishDate],
  manga: (id: number, locale: Locale) => ['manga', id, locale],
  mangaRecommendations: (userId: string, limit: number, locale: string) => [
    'me',
    'manga-recommendations',
    userId,
    limit,
    locale,
  ],
  searchSuggestions: (query: string, locale: string, limit?: number) => ['search', 'suggestions', locale, query, limit],
  censorshipSuggestions: (query: string, locale: string) => ['censorship', 'suggestions', locale, query],
  postsBase: ['posts'],
  followingPosts: ['posts', PostFilter.FOLLOWING],
  posts: (filter: PostFilter, mangaId?: number, username?: string, locale?: string) => [
    'posts',
    filter,
    { mangaId, username, locale },
  ],
  realtimeAnalytics: ['realtime-analytics'],
  trendingKeywords: (locale: string) => ['trending-keywords', locale],
  tag: (category: string, page: number, locale: string) => ['tag', category, page, locale],
  webtoonEpisode: (provider: string, domain: string, path: string) => ['webtoon', 'episode', provider, domain, path],
  webtoonList: (provider: string, domain: string) => ['webtoon', 'list', provider, domain],
  webtoonSeries: (provider: string, domain: string, path: string) => ['webtoon', 'series', provider, domain, path],

  proxyBase: ['proxy'],
  search: (searchParams: URLSearchParams, locale: Locale) => [
    ...QueryKeys.proxyBase,
    'search',
    locale,
    Object.fromEntries(searchParams),
  ],
  proxyKRandomBase: ['proxy', 'k', 'random'],
  proxyKRandom: (searchParams: URLSearchParams, locale: Locale) => [
    ...QueryKeys.proxyKRandomBase,
    locale,
    Object.fromEntries(searchParams),
  ],

  chatThreads: ['chat', 'threads'],
  chatStudio: ['chat', 'studio'],
  chatStudioEarnings: ['chat', 'studio', 'earnings'],
  chatArtist: (handle: string) => ['chat', 'artist', handle],
  paymentMethods: ['billing', 'payment-methods'],
  billingSubscriptions: ['billing', 'subscriptions'],
  billingPayments: ['billing', 'payments'],
  chatMessages: (handle: string) => ['chat', 'messages', handle],
  chatReplies: (handle: string, messageId: string) => ['chat', 'replies', handle, messageId],
}
