import { Locale, type PublicLocale } from '../locale'

export const TOP_MANGA_PER_PAGE = 30
export const REALTIME_PAGE_VIEW_MIN_THRESHOLD = 10
export const REALTIME_PAGE_RANKING_LIMIT = 20

// apps/web 고정 라우트의 Metadata.*.title 문자열과 동기화해요
const STATIC_PAGE_TITLES: Record<PublicLocale, string[]> = {
  [Locale.KO]: [
    '로그인',
    '회원가입',
    '검열',
    '후원',
    '알림',
    '이야기',
    '설정',
    '19세 미만 이용 제한 안내',
    '2257 컴플라이언스 안내',
    '저작권/DMCA 신고',
    '개인정보 처리방침',
    '이용약관',
    '청소년보호정책',
    '오늘의 운세',
    '신작',
    '랜덤',
    '추천 작품',
    '태그',
    '리보 내역',
    '리보',
    '룰렛',
    '리보 상점',
    '광고 수익 통계',
    '북마크',
    '서재',
    '감상 기록',
    '공개 서재',
    '작품 평가',
    '앱으로 사용하기',
    'AI 채팅',
    '새해 카운트다운',
    '후원 랭킹',
    '실시간',
    '검색',
  ],
  [Locale.EN]: [
    'Log in',
    'Sign up',
    'Censor',
    'Donation',
    'Notifications',
    'Posts',
    'Settings and privacy',
    'Under-19 Access Restriction Notice',
    '2257 Compliance Notice',
    'Copyright/DMCA Reports',
    'Privacy Policy',
    'Terms of Service',
    'Youth Protection Policy',
    "Today's Fortune",
    'New',
    'Random',
    'Recommended Manga',
    'Tags',
    'Libo History',
    'Libo',
    'Roulette',
    'Libo Shop',
    'Ad Revenue Stats',
    'Bookmarks',
    'Library',
    'Viewing History',
    'Public Libraries',
    'Manga Ratings',
    'Use as an App',
    'AI Chat',
    'New Year Countdown',
    'Donation Ranking',
    'Realtime',
    'Search',
  ],
  [Locale.JA]: [
    'ログイン',
    '新規登録',
    '検閲',
    '支援',
    '通知',
    'ストーリー',
    '設定',
    '19歳未満の利用制限に関するお知らせ',
    '2257 コンプライアンス案内',
    '著作権/DMCA 通報',
    'プライバシーポリシー',
    '利用規約',
    '青少年保護ポリシー',
    '今日の運勢',
    '新着',
    'おまかせ',
    'おすすめ作品',
    'タグ',
    'Libo 履歴',
    'Libo',
    'ルーレット',
    'Libo ショップ',
    '広告収益統計',
    'ブックマーク',
    'ライブラリ',
    '閲覧履歴',
    '公開ライブラリ',
    '作品評価',
    'アプリで使う',
    'AIと話す',
    '新年カウントダウン',
    '支援ランキング',
    'リアルタイム',
    '検索',
  ],
  [Locale.ZH_CN]: [
    '登录',
    '注册',
    '屏蔽',
    '赞助',
    '通知',
    '动态',
    '设置',
    '未满 19 岁访问限制说明',
    '2257 合规说明',
    '版权/DMCA 举报',
    '隐私政策',
    '使用条款',
    '青少年保护政策',
    '今日运势',
    '新作',
    '随机',
    '推荐作品',
    '标签',
    'Libo 明细',
    'Libo',
    '转盘',
    'Libo 商店',
    '广告收益统计',
    '书签',
    '书库',
    '阅读记录',
    '公开书库',
    '作品评分',
    '作为应用使用',
    'AI 聊天',
    '新年倒计时',
    '赞助排行',
    '实时',
    '搜索',
  ],
}

// apps/web Metadata.ranking title 템플릿(metric × period)과 동기화해요
const RANKING_PAGE_TITLES: Record<
  PublicLocale,
  { format: (period: string, metric: string) => string; metrics: string[]; periods: string[] }
> = {
  [Locale.KO]: {
    format: (period, metric) => `${period} ${metric} 순위`,
    metrics: ['조회', '북마크', '서재', '별점'],
    periods: ['일간', '주간', '월간', '분기', '연간'],
  },
  [Locale.EN]: {
    format: (period, metric) => `${period} ${metric} Ranking`,
    metrics: ['Views', 'Bookmarks', 'Libraries', 'Ratings'],
    periods: ['Daily', 'Weekly', 'Monthly', 'Quarterly', 'Yearly'],
  },
  [Locale.JA]: {
    format: (period, metric) => `${period} ${metric} ランキング`,
    metrics: ['閲覧', 'ブックマーク', 'ライブラリ', '評価'],
    periods: ['日間', '週間', '月間', '四半期', '年間'],
  },
  [Locale.ZH_CN]: {
    format: (period, metric) => `${period}${metric}排行`,
    metrics: ['浏览', '书签', '书库', '评分'],
    periods: ['日榜', '周榜', '月榜', '季度榜', '年榜'],
  },
}

export const REALTIME_EXCLUDED_PAGE_TITLES: ReadonlySet<string> = new Set([
  '403 Forbidden',
  '불러오는 중',
  ...Object.values(STATIC_PAGE_TITLES).flat(),
  ...Object.values(RANKING_PAGE_TITLES).flatMap(({ format, metrics, periods }) =>
    periods.flatMap((period) => metrics.map((metric) => format(period, metric))),
  ),
])
