export const MAX_CRITERIA_NAME_LENGTH = 32
export const MAX_CRITERIA_PER_USER = 20
export const MAX_NOTIFICATION_CRITERIA_CONDITIONS = 20
export const MAX_NOTIFICATION_COUNT = 100

export const NOTIFICATION_PER_PAGE = 25
