export type CreateProblemDetailsResponseOptions = ProblemDetailsOptions & {
  headers?: HeadersInit
}

export type InvalidParam = {
  name: string
  /** 기계 판별용 코드 — Zod 이슈 코드(too_small 등) 또는 refine params.code. 클라이언트가 로케일 카피로 변환한다. */
  code: string
  /** dev-facing 진단 문구 — 사용자에게 표시하지 않는다. */
  reason?: string
  minimum?: number
  maximum?: number
}

export type ProblemDetails = {
  /**
   * A URI reference that identifies the problem type.
   * We use: https://<origin>/problems/<code>
   */
  type: string
  /**
   * 문제 유형(code)의 사람용 요약 — 발생 건마다 바뀌지 않는다(RFC 9457).
   * code 없는 generic 문제는 status phrase가 기본값. dev-facing이며 사용자에게 표시하지 않는다.
   */
  title: string
  /**
   * The HTTP status code generated by the origin server for this occurrence.
   */
  status: number
  /**
   * 이 발생 건(occurrence)에 특정한 dev-facing 진단 — 동적 값이나 코드 없는 분기 설명.
   * 사용자에게 표시하지 않는다(사용자 카피는 웹이 code로 변환).
   */
  detail?: string
  /**
   * A URI reference that identifies the specific occurrence of the problem.
   */
  instance?: string
  /**
   * Extension members defined by RFC 9457.
   */
  [key: string]: unknown
}

export type ProblemDetailsOptions = {
  code?: string
  detail?: string
  extensions?: Record<string, unknown>
  instance?: string
  status: number
  title?: string
}

export type ValidationProblemDetails = ProblemDetails & {
  invalidParams?: InvalidParam[]
}

export const PROBLEM_CONTENT_TYPE = 'application/problem+json'

// status에서 자동 파생되는 generic HTTP slug 테이블(제네릭 빌더 기본값). 도메인 코드 카탈로그는
// @sobok/contracts의 PROBLEM 이 소유하며, sobok API 호출부는 거기서 slug 를 명시적으로 준다.
const problemCodeByStatus: Partial<Record<number, string>> = {
  400: 'bad-request',
  401: 'unauthorized',
  403: 'forbidden',
  404: 'not-found',
  408: 'request-timeout',
  409: 'conflict',
  429: 'too-many-requests',
  499: 'client-aborted',
  502: 'bad-gateway',
  503: 'service-unavailable',
  504: 'gateway-timeout',
}

// title 미지정 시의 기본값 — 표준 HTTP reason phrase(로케일 중립·dev-facing). 이 패키지는 제네릭 RFC 9457
// 빌더이므로 제품 카피(로케일 문구)를 담지 않는다. sobok API는 호출부(@sobok/contracts PROBLEM)에서 title을 준다.
const reasonPhraseByStatus: Partial<Record<number, string>> = {
  400: 'Bad Request',
  401: 'Unauthorized',
  403: 'Forbidden',
  404: 'Not Found',
  408: 'Request Timeout',
  409: 'Conflict',
  429: 'Too Many Requests',
  499: 'Client Closed Request',
  500: 'Internal Server Error',
  502: 'Bad Gateway',
  503: 'Service Unavailable',
  504: 'Gateway Timeout',
}

export function createProblemDetailsResponse(
  request: string | Request | URL,
  options: CreateProblemDetailsResponseOptions,
): Response {
  const { headers: headersInit, ...problemOptions } = options
  const problem = getProblemDetails(request, problemOptions)
  const body = JSON.stringify(problem)

  const headers = new Headers(headersInit)
  headers.set('Content-Type', PROBLEM_CONTENT_TYPE)
  headers.set('Content-Length', String(Buffer.byteLength(body)))

  return new Response(body, {
    status: options.status,
    headers,
  })
}

export function getInvalidParams(problem: ProblemDetails | null | undefined): InvalidParam[] {
  if (problem == null || typeof problem !== 'object') {
    return []
  }

  const { invalidParams } = problem as ValidationProblemDetails

  if (!Array.isArray(invalidParams)) {
    return []
  }

  return invalidParams.filter((param): param is InvalidParam => {
    if (typeof param !== 'object' || param === null) {
      return false
    }

    const record = param as Record<string, unknown>
    return typeof record.name === 'string' && typeof record.code === 'string'
  })
}

/** problem `type` URL(`https://<origin>/problems/<code>`)에서 code slug를 추출한다. */
export function getProblemCode(typeUrl: string): string | null {
  const marker = '/problems/'
  const index = typeUrl.lastIndexOf(marker)

  if (index === -1) {
    return null
  }

  const slug = typeUrl.slice(index + marker.length)

  if (slug.length === 0 || slug.includes('/')) {
    return null
  }

  try {
    return decodeURIComponent(slug)
  } catch {
    return slug
  }
}

export function isProblemDetails(value: unknown): value is ProblemDetails {
  if (typeof value !== 'object' || value === null) {
    return false
  }

  const record = value as Record<string, unknown>
  return (
    typeof record.type === 'string' &&
    typeof record.title === 'string' &&
    typeof record.status === 'number' &&
    (record.detail === undefined || typeof record.detail === 'string') &&
    (record.instance === undefined || typeof record.instance === 'string')
  )
}

export function isProblemDetailsContentType(contentType: string | null | undefined): boolean {
  return contentType?.toLowerCase().split(';', 1)[0].trim() === PROBLEM_CONTENT_TYPE
}

export function isProblemType(typeUrl: string, code: string): boolean {
  const suffix = `/problems/${encodeURIComponent(code)}`

  try {
    return new URL(typeUrl).pathname === suffix
  } catch {
    return typeUrl.endsWith(suffix)
  }
}

function getProblemCodeFromStatus(status: number): string {
  const code = problemCodeByStatus[status]

  if (code) {
    return code
  }

  if (status >= 400 && status < 500) {
    return 'bad-request'
  }

  return 'internal-server-error'
}

function getProblemDetails(request: string | Request | URL, options: ProblemDetailsOptions): ProblemDetails {
  const url = getRequestUrl(request)
  const instance = options.instance ?? url.pathname + url.search
  const code = options.code ?? getProblemCodeFromStatus(options.status)

  return {
    ...options.extensions,
    type: getProblemTypeUrl(url.origin, code),
    title: options.title ?? getReasonPhrase(options.status),
    status: options.status,
    detail: options.detail,
    instance,
  }
}

function getProblemTypeUrl(origin: string, code: string): string {
  const safeOrigin = trimTrailingSlashes(origin)
  const safeCode = encodeURIComponent(code)

  try {
    const url = new URL(safeOrigin)
    url.protocol = 'https:'
    return `${url.origin}/problems/${safeCode}`
  } catch {
    return `${safeOrigin}/problems/${safeCode}`
  }
}

function getRequestUrl(request: string | Request | URL): URL {
  if (request instanceof Request) {
    return new URL(request.url)
  }

  return new URL(request)
}

function getReasonPhrase(status: number): string {
  const phrase = reasonPhraseByStatus[status]

  if (phrase) {
    return phrase
  }

  if (status >= 500) {
    return 'Internal Server Error'
  }

  return 'Bad Request'
}

function trimTrailingSlashes(value: string): string {
  let end = value.length

  while (end > 0 && value[end - 1] === '/') {
    end -= 1
  }

  return value.slice(0, end)
}
