/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=/dev/null --include-runtime=false --strict-vars=false --env-interface=AccountsPublicBindings worker-configuration.generated.d.ts` (hash: 01a0bbae29d97f195d65cdf4e7ab84da)
interface __BaseEnv_AccountsPublicBindings {
	ASSETS: Fetcher;
	DATABASE: Service /* entrypoint AccountsService from database-stg */ | Service /* entrypoint AccountsService from database */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface StgEnv {
		ASSETS: Fetcher;
		DATABASE: Service /* entrypoint AccountsService from database-stg */;
	}
	interface Env extends __BaseEnv_AccountsPublicBindings {}
}
interface AccountsPublicBindings extends __BaseEnv_AccountsPublicBindings {}
